### ISSUE TITLE
Self-loop for integer variables is accepted

### ISSUE THREAD

**Issue by hsadeghidw** [dwavesystems/dimod#1004]
**Description**
This may or may not be a bug. In a `QuadraticModel` self-loop is accepted for integer variables.

**Expected Behavior**
Either raise an error early, or support self-loops/quadratic, square terms

```
import dimod
from dwave.system import LeapHybridCQMSampler
x = [dimod.Integer(f'p_v_{j}', lower_bound=0, upper_bound=5) for j in range(3)]
cqm = dimod.ConstrainedQuadraticModel()
cqm.set_objective(dimod.quicksum([v * v for v in x]))
print(cqm.objective.shape)
print(cqm.objective)
```

**Additional Context**
The user doesn't get any warning that self-loop or square terms aren't supported for integer variables.

**Comment by arcondello** [comment]
Since they are well defined we do accept them. We provide a `CQM.substitute_self_loops` method (https://github.com/dwavesystems/dimod/pull/948) for any solvers that do not support them.
