### ISSUE TITLE
`CQM.is_equal()` or similar

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#1012]
Probably also want some sort of tolerance parameter.

Requested by @vgoliber

**Comment by vgoliber** [comment]
Something similar to this would be wonderful: https://github.com/dwavesystems/dimod/blob/96928a68637ec1d2af5e19e0678417b164ef237d/dimod/binary/binary_quadratic_model.py#L1288

**Comment by arcondello** [comment]
Though I am currently questioning past Alex's judgement for making those separate methods rather than having `places` as a parameter on `.is_equal()`.
