### ISSUE TITLE
dimod built from source > 0.10.8 not importing QuadraticModel

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#1055]
**Description**
Building from source dimod for current version of main (SHA https://github.com/dwavesystems/dimod/commit/927da3cd60c7ca3dfa79d1c632c1db43170cdcd5) results in import error:

```
from dimod import QuadraticModel
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-ee540fc6d89c> in <module>
----> 1 from dimod import QuadraticModel

...

---> 15 from dimod.bqm.adjvectorbqm import AdjVectorBQM
     16 from dimod.bqm.construction import as_bqm
     17 from dimod.bqm.adjdictbqm import AdjDictBQM

ModuleNotFoundError: No module named 'dimod.bqm.adjvectorbqm'
```

**Steps To Reproduce**

* New venv
* clone dimod
* update to latest pip
* install requirements
* python setup.py install 

**Expected Behavior**
Current dimod should work

**Environment**
 - OS: Ubuntu 16
 - Python version: 3.7

**Additional Context**
Updated pip

**Comment by arcondello** [comment]
That error comes as part of the build command? Or when you try to use it?

**Comment by JoelPasvolsky** [comment]
It builds without error, that happens when trying to use it

**Comment by arcondello** [comment]
What directory are you running commands from? You would get this error if you were still running from the root of dimod, since it would use the local file structure rather than the installed one.

**Comment by JoelPasvolsky** [comment]
Yes, thank you, that is the cause (local file structure)

**Comment by arcondello** [comment]
Closing issue as user error in that case.
