### ISSUE TITLE
Upper -> lower triangular change in BQM representation breaks other dwave components

### ISSUE THREAD

**Issue by quosta** [dwavesystems/dimod#1057]
**Description**
I noticed that the BQM is now stored as a lower triangular matrix. At least this is what I get when I instantiate a random 5x5 matrix. 

BUG 1) The embedding function from dwave.embedding fails to provide a similar lower triangular matrix. What is going on here? 

BUG 2) Also I would like to have the BQM matrix to analyze. If I run the old method `bqm.to_numpy_matrix()` - which is now deprecated but still present with no alternative - I get an upper triangular matrix. I guess I can use `bqm.to_numpy_matrix().T` as for now.

**Steps To Reproduce**

As for BUG 1, just embed the BQM.  

```
import dimod
import numpy as np
import minorminer
from dwave.embedding import embed_bqm, EmbeddedStructure
from dwave.system.samplers import DWaveSampler

mat = np.random.rand(5,5) #square mat
mat = (mat + mat.T) / 2 #make it symmetrical
bqm = dimod.BQM(A,"BINARY") #lower triang bqm

sampler = DWaveSampler(solver='DW_2000Q_6')
topology = sampler.to_networkx_graph()
emb = minorminer.find_embedding(dimod.to_networkx_graph(bqm), topology)
embedding = EmbeddedStructure(topology.edges(), emb)
new_bqm = embed_bqm(bqm,embedding) # ??

```

**Expected Behavior**
Not sure, the new_bqm is it not supposed to be lower triangular as well?

Before embedding BQM
![image](https://user-images.githubusercontent.com/85477370/143781764-ef9dfad7-f0ba-459b-8f5d-eb4f3db1e353.png)

After embedding BQM
![image](https://user-images.githubusercontent.com/85477370/143781789-730465b2-14f5-4a3f-b82e-4028be17f4db.png)

**Comment by quosta** [comment]
I was wrong, the lower triangular matrices are produced only if a dense square matrix is provided in the initialization. Generally it seems that the BQM do not enforce either i > j nor i < j. Even the method bqm.to_qubo() does not produce a dict that follows i < j as it is often written in the QUBO formulations. It seems that there are no issues with the other components, as long as for each (i, j) there isn't another (j, i).

**Comment by arcondello** [comment]
Hi @quosta,

I think the point of confusion here is that the BQM object actually encodes _both_ the upper and lower triangle simultaneously. In general I would not recommend poking around in the private attributes like this, but it is probably useful to look inside the implementation of the `DictBQM`.
```python
In [1]: import dimod

In [2]: bqm = dimod.DictBQM.from_ising({'a': 1}, {('a', 'b'): 2, ('b', 'c'): 3})

In [3]: bqm.data._adj
Out[3]: {'a': {'a': 1, 'b': 2}, 'b': {'b': 0, 'a': 2, 'c': 3}, 'c': {'c': 0, 'b': 3}}
```
here you can see that we store the biases in an [adjacency structure](https://en.wikipedia.org/wiki/Adjacency_list). So each bias is saved twice.

We then de-duplicate when we convert to a QUBO dictionary, for instance with `bqm.to_qubo()` or when printing or when iterating with `bqm.iter_quadratic()`.
