### ISSUE TITLE
bqm.to_networkx_graph deprecation message confusing

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#1102]
**Description**
```
G16 = bqm.to_networkx_graph()
ipython:1: DeprecationWarning: BinaryQuadraticModel.to_networkx_graph() is deprecated since dimod 0.10.0, use bqm.to_networkx_graph() instead.
```

Would be clearer to say `use dimod.to_networkx_graph(bqm)` instead.

**Additional Context**
`G16 =dimod.to_networkx_graph(bqm)` works nicely.

**Comment by arcondello** [comment]
I think that's a typo, and should be `dimod.to_networkx_graph(bqm)`
