### ISSUE TITLE
generators.anti_crossing_loops connects 8-node structures by -1-biased nodes only

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#1103]
**Description**

I don't know if it matters or not: https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/generated/dimod.generators.anti_crossing_loops.html says it reproduces the problem of https://www.nature.com/articles/ncomms2920, but the former connects its 8-node structures together by linking -1-biased nodes while the latter links 0-bias and-1-bias nodes.

![image](https://user-images.githubusercontent.com/34041130/153637311-10204439-e045-4a07-bdfd-ca129be2c3af.png)

**Steps To Reproduce**
```
>>> bqm16 = dimod.generators.anti_crossing_loops(16)
>>> g16 = dimod.to_networkx_graph(bqm16)
>>> colors = [g16.nodes[n]['bias'] for n in g16.nodes]
>>> nx.draw(g16, node_color=colors, with_labels=True, cmap=plt.cm.autumn)
```
**Expected Behavior**
That's what I want to know

**Comment by JoelPasvolsky** [comment]
Here is a comparison between the original problem, which can be embedded directly into two Chimera unit cells, and the Chimera-embedded BQM returned from dimod.generators.anti_crossing_loops(16):

![image](https://user-images.githubusercontent.com/34041130/153517384-194131a6-bae5-466f-97c3-2ba04b7465cd.png)


![image](https://user-images.githubusercontent.com/34041130/153517344-76f89353-6b01-44df-ab3e-fa65274b9d80.png)
In the second, zero bias is orange, +1 is yellow, -1 is red

**Comment by jackraymond** [comment]
docstring is pretty difficult to understand. The principle underlying the tight anti-crossing is the existence of a unique ground state in combination with a highly degenerate (and well-disconnected in terms of Hamming distance) 1st excited state manifold. From this principle we can probably establish the proper intention of the generalization beyond the specific case presented in the cited paper (n=16) and correct the general case.

**Comment by JoelPasvolsky** [comment]
@jackraymond, https://github.com/dwavesystems/dimod/pull/1109 updates the ``anti_crossing_loops`` docstring, but was unclear to me the intended fidelity to the paper's problem.

**Comment by JoelPasvolsky** [comment]
@jackraymond I think you're right about same underlying principal but different implementation. The embedded original problem, 
![image](https://user-images.githubusercontent.com/34041130/153664648-c94c0cb8-cfc8-4dd5-aa0a-fb13009adca5.png)
has an all -1 ground state at energy -20 and degenerate solutions at energy -16.
The embedded ``anti_crossing_loops`` problem,
![image](https://user-images.githubusercontent.com/34041130/153664858-9ba2ed11-0fcf-48d9-962f-9255f1b7fc5d.png)
has its all +1 ground state at energy -20 and degenerate solutions at -16.

**Comment by jackraymond** [comment]
After side discussion with @JoelPasvolsky , I think this can probably be addressed with docstring changes. The differences between the models are non-trivial, but seem to be superficial for practical purposes, something like:
'The low-energy state space consists of a unique ground state (all +1) and a well separated (in Hamming distance, and by an energy barrier) degenerate 1st excited state (centered at all -1).  These features are sufficient to yield a small anti-crossing when employed in a transverse field annealing process. A closely related approach is employed in this paper: as cited'
