### ISSUE TITLE
generators.frustrated_loop should output an error message when good_cycles < num_cycles

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#1108]
**Description**
When the generator fails to find the requested number of cycles it raises the error without a message. One can see the code line that triggered the error, and it's reasonably clear, but nicer to produce a proper message

**Steps To Reproduce**
```
>>> bqm = dimod.generators.frustrated_loop(4, 3, R=1, seed=1)
RuntimeError:
```
**Expected Behavior**
A clear and concise error message.

**Comment by arcondello** [comment]
Closed by https://github.com/dwavesystems/dimod/pull/1109
