### ISSUE TITLE
Relabeling creates inconsistent BQMs

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#1110]
**Description**
Relabeling can create BQMs that are inconsistent with generated BQMs:

```
>>>  bqm = dimod.BinaryQuadraticModel({'a': 1, 'b': 2}, {('a', 'b'): 1.5}, 'BINARY')
>>> bqm.relabel_variables({'a': 'c', 'b': 'c'})
>>> print(bqm.linear, bqm.quadratic)
{'c': 2.0, 'c': 2.0} {('c', 'c'): 1.5}
```

In comparison:

```
>>> bqm = dimod.BinaryQuadraticModel({'c': 1, 'c': 2}, {('c', 'c'): 1.5}, 'BINARY')
>>> print(bqm.linear, bqm.quadratic)
{'c': 3.5} {}
```

**Expected Behavior**
Consistent treatment of a variable set in multiple places. For the given example, it's noticeable, but in relabeling large numbers of variables in a big BQM, this might not end well

**Environment**
dimod version here is 0.10.10

**Comment by arcondello** [comment]
Also `{'c': 1, 'c': 2}` in your second example is just `{'c': 2}`. You can get something similar to what you're looking for with `bqm.contract_variables(''a, 'b')`.
