### ISSUE TITLE
Summation ranges for QM: i<=j versus i<j

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#1114]
**Description**
[class QuadraticModel](https://github.com/dwavesystems/dimod/blob/655e330d5813546630191a7b1e594e63d240a33e/dimod/quadratic/quadratic_model.py#L127) defines the summation range for quadratic coefficients as :math:`\sum_{i<j} b_{i, j} x_i x_j`, and that is accurate for binary variables but quadratic models allow self loops for int variables, so it seems to me the summation for QMs should be :math:`\sum_{i \le j} b_{i, j} x_i x_j`

**Steps To Reproduce**

```
>>> from dimod import QuadraticModel
>>> qm = QuadraticModel({}, {(0, 0): 1}, 0, {0: "INTEGER"})
```

**Expected Behavior**
Update definition as needed.

**Additional Context**
https://docs.ocean.dwavesys.com/en/stable/concepts/cqm.html

**Comment by arcondello** [comment]
Feel free to make the change. Probably just going to `<=` and adding a note that self-loops for binary and spin variables are not allowed.
