### ISSUE TITLE
Add support for coefficients in scientific notation to LP file parser

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#1132]
Currently `CQM.from_lp_file` (using grammar from `make_lp_grammar`) supports coefficients expressed as decimal numbers:

https://github.com/dwavesystems/dimod/blob/1f634676635b6df17c70e589af87556a83fc4084/dimod/serialization/lp.py#L68

but not scientific/exponential notation, for example:
```
Minimize
  obj: 2e3 x0 + 2.1e-04 x0^2
Subject To
  x0 <= 1
General
  x0
End
```
or
```
Minimize
  obj: 2e3 x0 + [4.1e-02 x0*x0]/2
Subject To
  x0 <= 1
General
  x0
End
```

Motivation: [QPLIB](https://qplib.zib.de/) contains problems with coefficients expressed in scientific notation.

**Comment by arcondello** [comment]
Putting this here so I don't forget, it looks like SciPy might be addings support for reading LP files https://github.com/scipy/scipy/issues/14593. It also appears that they use [HiGHS](https://github.com/ERGO-Code/HiGHS) for their support.

**Comment by randomir** [comment]
No one seems to be working on that SciPy feature, so it might be worth considering contributing #1182 (i.e. some variant of it) to SciPy?

**Comment by arcondello** [comment]
> No one seems to be working on that SciPy feature, so it might be worth considering contributing #1182 (i.e. some variant of it) to SciPy?

See response https://github.com/dwavesystems/dimod/pull/1182#issuecomment-1117474634 tldr; yes but need a few things to happen first
