### ISSUE TITLE
Inconsistent handling of conflicting bounds

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#1141]
**Description**
I can set conflicting bounds if I first add a constraint with bounded variables and then set the variable's bound in the CQM but not if I first set the CQM bound and then add a constraint. 

**Steps To Reproduce**
```
>>> cqm = dimod.ConstrainedQuadraticModel()
>>> i = dimod.Integer("i", lower_bound=3)
>>> cqm.add_constraint_from_comparison(i >= 4, label="C1")
'C1'
>>> cqm.set_lower_bound("i", 5)
>>> cqm.add_constraint_from_comparison(i <= 8, label="C2")
---------------------------------------------------------------------------
ValueError: the specified lower bound, 3.0, for variable 'i' is different than the existing lower bound, 5
```

**Expected Behavior**
Consistent handling of these two cases.

**Comment by arcondello** [comment]
This is intended behavior. Since you're overriding the lower bound, subsequently adding new constraints have to match the variable domain.
