### ISSUE TITLE
Get consistent error message in `binary_encoding` generator

### ISSUE THREAD

**Issue by alexzucca90** [dwavesystems/dimod#1150]
**Description**
If integers have an upper_bound of 1, an error is raised, but the error message says 1 is actually allowed.
```
    if upper_bound <= 1:
        raise ValueError("upper_bound must be greater than or equal to 1, "
                         f"received {upper_bound}")
```

**Steps To Reproduce**
```
from dimod.generators import binary_encoding
bqm = binary_encoding('i', 1)
```

**Expected Behavior**
Either change the message to "larger equal than 2" or "larger than 1". Alternatively, upper bound of 1 can directly return a binary variable.

**Comment by arcondello** [comment]
Fixed by https://github.com/dwavesystems/dimod/commit/9fba14a415239f3153d0076854e4090250804e6c which I accidentally pushed directly to main :flushed:
