### ISSUE TITLE
Converting BQM to CQM using cqm = ConstrainedQuadraticModel().from_bqm(bqm)

### ISSUE THREAD

**Issue by ACE07-Sev** [dwavesystems/dimod#1153]
**Description**
I'm trying to create a CQM from an existing BQM, but when I run the code I get this error :
Traceback (most recent call last):
  File "C:\Users\elmm\Desktop\MIT OCW Codes\CQM.py", line 189, in <module>
    best_solution = solve_bqm(cqm, x, SimulatedAnnealingSampler())
  File "C:\Users\elmm\Desktop\MIT OCW Codes\CQM.py", line 147, in solve_bqm
    response = sampler.sample(bqm, **kwargs)
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\neal\sampler.py", line 206, in sample
    bqm = bqm.change_vartype(dimod.SPIN, inplace=False)
AttributeError: 'ConstrainedQuadraticModel' object has no attribute 'change_vartype'

**Steps To Reproduce**
here is my full code, it has two methods, one building the BQM and the other as solver/sampler. 
import os

os.chdir('..')
from dimod import ConstrainedQuadraticModel, BinaryQuadraticModel
from neal import SimulatedAnnealingSampler
from dwave.system import LeapHybridSampler
import numpy as np

def build_setcover_bqm(U, V, verbose=False):
    """Construct BQM for the set cover problem
    Args:
        U (array-like):
            A set of elements defining the universe
        V (array of sets):
            Array of subsets
    Returns:
        Binary quadratic model instance
        x: variable
    """

    # Create indicator variables
    I = []
    for i in range(len(V)):
        I.append([1 if U[a] in V[i] else 0 for a in range(len(U))])

    if verbose:
        print('Indicator variables: I_i,a', I)

    # Lagrange multipliers A>B>0
    A = 2
    B = 1

    ##@  Binary Quadratic Model @##
    bqm = BinaryQuadraticModel('BINARY')

    # Add linear terms
    # x linear terms
    x = [bqm.add_variable('x_' + str(i + 1), A * sum(I[i]) + B) for i in range(0, len(V))]
    if verbose:
        print('x variables:', x)

    # y_am linear terms
    y = []
    for a in range(1, len(U) + 1):
        y.append(
            [bqm.add_variable('y_(' + str(a) + ', ' + str(m) + ')', A * (m ** 2 - 1)) for m in range(1, len(V) + 1)])
    if verbose:
        print('y variables:', y)

    # Add quadratic terms

    # x_i-x_j terms
    for i in range(1, len(V) + 1):
        for j in range(i + 1, len(V) + 1):
            key = ('x_' + str(i), 'x_' + str(j))
            bqm.quadratic[key] = 2 * A * np.dot(np.array(I[i - 1]), np.array(I[j - 1]))

    # y_am - y_an terms
    for m in range(1, len(V) + 1):
        for n in range(m + 1, len(V) + 1):
            for a in range(1, len(U) + 1):
                key = ('y_(' + str(a) + ', ' + str(m) + ')', 'y_(' + str(a) + ', ' + str(n) + ')')
                bqm.quadratic[key] = 2 * A * (1 + m * n)

    # x_i-y_am terms
    for i in range(1, len(V) + 1):
        for m in range(1, len(V) + 1):
            for a in range(1, len(U) + 1):
                key = ('x_' + str(i), 'y_(' + str(a) + ', ' + str(m) + ')')
                bqm.quadratic[key] = -2 * A * m * I[i - 1][a - 1]
    return bqm, x

def solve_bqm(bqm, x, sampler, **kwargs):
    response = sampler.sample(bqm, **kwargs)
    energies = response.record.energy
    best_energy = energies[0]
    best_solution = response.first.sample
    best_solution = [best_solution[i] for i in x]
    print(best_solution)
    print(f'Energy: {best_energy}')

    return best_solution, best_energy

# Define a simple set cover problem
U = list(set(np.random.randint(10, size=10)))

V = [set(U[i] for i in np.random.randint(len(U), size=(8))) for j in range(5)]

print('The universe is', U)
print('Number of elements in the universe: {:d}'.format(len(U)))

print('There are {:d} collections:'.format(len(V)), V)
print('Number of sets: N={:d}'.format(len(V)))

bqm,x = build_setcover_bqm(U, V)
cqm = ConstrainedQuadraticModel().from_bqm(bqm)
best_solution = solve_bqm(cqm, x, SimulatedAnnealingSampler())

bqm,x = build_setcover_bqm(U, V)
cqm = ConstrainedQuadraticModel().from_bqm(bqm)
best_solution = solve_bqm(cqm, x, LeapHybridSampler())

**Expected Behavior**
I expected the code to output the results from the annealing through CQM. I'm quite new to this suite and would really appreciate the correction on code to get the CQM of this BQM. Can you kindly walk me through converting this method to create a CQM please?

**Comment by arcondello** [comment]
Hi @ACE07-Sev

I believe the problem is not the CQM you've made from a BQM but the fact that `neal.SimulatedAnnealingSampler` accepts BQMs, not CQMs. If you just pass your original BQM to it that should work fine

**Comment by ACE07-Sev** [comment]
hi, what sampler will work for CQM so I can try to see if it works with that?

**Comment by ACE07-Sev** [comment]
Hi, I tried this sampler, but got error again :

Traceback (most recent call last):
  File "C:\Users\elmm\Desktop\MIT OCW Codes\CQM_2.py", line 111, in <module>
    sampleset = ExactCQMSolver().sample_cqm(cqm)
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dimod\reference\samplers\exact_solver.py", line 262, in sample_cqm
    cases = _all_cases_cqm(cqm)
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dimod\reference\samplers\exact_solver.py", line 316, in _all_cases_cqm
    c1 = np.array(np.meshgrid(*cases))
  File "<__array_function__ internals>", line 5, in meshgrid
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\function_base.py", line 4288, in meshgrid
    output = [np.asanyarray(x).reshape(s0[:i] + (-1,) + s0[i + 1:])
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\function_base.py", line 4288, in <listcomp>
    output = [np.asanyarray(x).reshape(s0[:i] + (-1,) + s0[i + 1:])
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\_asarray.py", line 171, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
MemoryError

this was my sampler code :
cqm, x = build_setcover_cqm(U, V)
sampleset = ExactCQMSolver().sample_cqm(cqm)

**Comment by ACE07-Sev** [comment]
Hi, would you kindly see if this one works ?

`import os

import dimod

os.chdir('..')
from dimod import ConstrainedQuadraticModel, Integer, BinaryQuadraticModel, ExactCQMSolver
from dwave.system import LeapHybridCQMSampler
from dimod import ExactSolver
from neal import SimulatedAnnealingSampler
from itertools import combinations
from dwave.system import LeapHybridSampler
import numpy as np
import pandas as pd


# from utils.data import read_inventory_optimization_data
# from services.classical_optimizers import binary_supplier_optimizer

def build_setcover_cqm(U, V, verbose=False):
    """Construct CQM for the set cover problem
    Args:
        U (array-like):
            A set of elements defining the universe
        V (array of sets):
            Array of subsets
    Returns:
        Constrained quadratic model instance
        x: variable
    """

    # Create indicator variables
    I = []
    for i in range(len(V)):
        I.append([1 if U[a] in V[i] else 0 for a in range(len(U))])

    if verbose:
        print('Indicator variables: I_i,a', I)

    # Lagrange multipliers A>B>0
    A = 2
    B = 1

    ##@  Constrained Quadratic Model @##
    cqm = ConstrainedQuadraticModel()

    # Add linear terms
    # x linear terms
    [cqm.add_variable('x_' + str(i + 1), 'INTEGER') for i in range(0, len(V))]
    x = [cqm.objective.set_linear('x_' + str(i + 1), A * sum(I[i]) + B) for i in range(0, len(V))]
    if verbose:
        print('x variables:', x)
    print(str(cqm.variables))
    # y_am linear terms
    y = []
    for a in range(1, len(U) + 1):
        [cqm.add_variable('y_(' + str(a) + ', ' + str(m) + ')', 'INTEGER') for m in range(1, len(V) + 1)]
        y.append(
            [cqm.objective.set_linear('y_(' + str(a) + ', ' + str(m) + ')', A * (m ** 2 - 1)) for m in range(1, len(V) + 1)])
    if verbose:
        print('y variables:', y)

    # Add quadratic terms

    # x_i-x_j terms
    for i in range(1, len(V) + 1):
        for j in range(i + 1, len(V) + 1):
            key = ('x_' + str(i), 'x_' + str(j))
            cqm.objective.set_quadratic = ('x_' + str(i), 'x_' + str(j),2 * A * np.dot(np.array(I[i - 1]), np.array(I[j - 1])))

    # y_am - y_an terms
    for m in range(1, len(V) + 1):
        for n in range(m + 1, len(V) + 1):
            for a in range(1, len(U) + 1):
                key = ('y_(' + str(a) + ', ' + str(m) + ')', 'y_(' + str(a) + ', ' + str(n) + ')')
                cqm.objective.set_quadratic = ('y_(' + str(a) + ', ' + str(m) + ')', 'y_(' + str(a) + ', ' + str(n) + ')',2 * A * (1 + m * n))

    # x_i-y_am terms
    for i in range(1, len(V) + 1):
        for m in range(1, len(V) + 1):
            for a in range(1, len(U) + 1):
                key = ('x_' + str(i), 'y_(' + str(a) + ', ' + str(m) + ')')
                cqm.objective.set_quadratic = ('x_' + str(i), 'y_(' + str(a) + ', ' + str(m) + ')',-2 * A * m * I[i - 1][a - 1])
    return cqm, x


def solve_cqm(cqm, x, sampler, **kwargs):
    response = sampler.sample(cqm, **kwargs)
    energies = response.record.energy
    best_energy = energies[0]
    best_solution = response.first.sample
    best_solution = [best_solution[i] for i in x]
    print(best_solution)
    print(f'Energy: {best_energy}')

    return best_solution, best_energy


# Define a simple set cover problem
U = list(set(np.random.randint(10, size=10)))

V = [set(U[i] for i in np.random.randint(len(U), size=(8))) for j in range(5)]

print('The universe is', U)
print('Number of elements in the universe: {:d}'.format(len(U)))

print('There are {:d} collections:'.format(len(V)), V)
print('Number of sets: N={:d}'.format(len(V)))

cqm, x = build_setcover_cqm(U, V)
best_solution = ExactCQMSolver().sample_cqm(cqm)`

**Comment by ACE07-Sev** [comment]
does this work? I can't run it because of the token error, but is it correct? Is it a correct CQM equivalent of the initial BQM? That's my task.

**Comment by ACE07-Sev** [comment]
> Hi @ACE07-Sev
> 
> I believe the problem is not the CQM you've made from a BQM but the fact that `neal.SimulatedAnnealingSampler` accepts BQMs, not CQMs. If you just pass your original BQM to it that should work fine

I have added some updates here which I'd immensely appreciate if you check out!!

**Comment by arcondello** [comment]
> hi, what sampler will work for CQM so I can try to see if it works with that?

The `ExactCQMSampler` will work for very very small problems with small integer ranges. Your other option is `LeapHybridCQMSampler` from [dwave-system](https://github.com/dwavesystems/dwave-system)
