### ISSUE TITLE
CQM from DQM using cqm = ConstrainedQuadraticModel.from_dqm(dqm)

### ISSUE THREAD

**Issue by ACE07-Sev** [dwavesystems/dimod#1156]
Does `cqm = ConstrainedQuadraticModel.from_dqm(dqm)` correctly create the CQM equivalent of an existing DQM with fixed and/or varying bounds?

here are the three methods which create the DQM :

def build_knapsack_dqm_fixedbound(values, weights, weight_capacity, bound, verbose=False):
    """Construct DQM for the generalized knapsack problem
    Args:
        values (array-like):
            Array of values associated with the items
        weights (array-like):
            Array of weights associated with the items
        weight_capacity (int):
            Maximum allowable weight
        bound(int):
            Maximum allowable pieces for each item
    Returns:
        Discrete quadratic model instance
        x: variable
    """
    bound += 1  # also take into account the value 0
    pieces = range(bound)

    # First guess the lagrange
    lagrange = max(values) * 0.5
    if verbose:
        print('lagrange:', lagrange)

    # Number of objects
    x_size = len(values)

    # Lucas's algorithm introduces additional slack variables to
    # handle the inequality. M+1 binary slack variables are needed to
    # represent the sum using a set of powers of 2.
    M = floor(log2(weight_capacity))
    num_slack_variables = M + 1

    # Slack variable list for Lucas's algorithm. The last variable has
    # a special value because it terminates the sequence.
    y = [2 ** n for n in range(M)]
    y.append(weight_capacity + 1 - 2 ** M)

    ##@  Discrete Quadratic Model @##
    dqm = DiscreteQuadraticModel()
    x = []
    # @ Add variables @##
    for k in range(x_size):
        x.append(dqm.add_variable(bound, label='x' + str(k)))

    for k in range(num_slack_variables):
        dqm.add_variable(2, label='y' + str(k))  # either 0 or 1

    ##@ Hamiltonian xi-xi terms ##
    for k in range(x_size):
        dqm.set_linear('x' + str(k), lagrange * (weights[k] ** 2) * (np.array(pieces) ** 2) - values[k] * pieces)

    # # Hamiltonian xi-xj terms
    for i in range(x_size):
        for j in range(i + 1, x_size):
            biases_dict = {}
            for piece1 in pieces:
                for piece2 in pieces:
                    biases_dict[(piece1, piece2)] = (2 * lagrange * weights[i] * weights[j]) * piece1 * piece2

            dqm.set_quadratic('x' + str(i), 'x' + str(j), biases_dict)

    # Hamiltonian y-y terms
    for k in range(num_slack_variables):
        dqm.set_linear('y' + str(k), lagrange * np.array([0, 1]) * (y[k] ** 2))

    # Hamiltonian yi-yj terms
    for i in range(num_slack_variables):
        for j in range(i + 1, num_slack_variables):
            dqm.set_quadratic('y' + str(i), 'y' + str(j), {(1, 1): 2 * lagrange * y[i] * y[j]})

    # Hamiltonian x-y terms
    for i in range(x_size):
        for j in range(num_slack_variables):
            biases_dict = {}
            for piece1 in pieces:
                biases_dict[(piece1, 1)] = -2 * lagrange * weights[i] * y[j] * piece1

            dqm.set_quadratic('x' + str(i), 'y' + str(j), biases_dict)

    return dqm, x

def build_knapsack_dqm_variablebound2(values, weights, weight_capacity, bound, verbose=False):
    """Construct DQM for the generalized knapsack problem
    Args:
        values (array-like):
            Array of values associated with the items
        weights (array-like):
            Array of weights associated with the items
        weight_capacity (int):
            Maximum allowable weight
        bound(int):
            Maximum allowable pieces for each item
    Returns:
        Discrete quadratic model instance
    """
    bound = [b + 1 for b in bound]  # also take into account the value 0
    #     pieces = range(bound)

    # First guess the lagrange
    lagrange = max(values) * 0.5
    if verbose:
        print('lagrange:', lagrange)

    # Number of objects
    x_size = len(values)

    # Lucas's algorithm introduces additional slack variables to
    # handle the inequality. M+1 binary slack variables are needed to
    # represent the sum using a set of powers of 2.
    M = floor(log2(weight_capacity))
    num_slack_variables = M + 1

    # Slack variable list for Lucas's algorithm. The last variable has
    # a special value because it terminates the sequence.
    y = [2 ** n for n in range(M)]
    y.append(weight_capacity + 1 - 2 ** M)

    ##@  Discrete Quadratic Model @##
    dqm = DiscreteQuadraticModel()

    x = []
    # @ Add variables @##
    for k in range(x_size):
        x.append(dqm.add_variable(bound[k], label='x' + str(k)))

    for k in range(num_slack_variables):
        dqm.add_variable(2, label='y' + str(k))  # either 0 or 1

    ##@ Hamiltonian xi-xi terms ##
    for k in range(x_size):
        pieces = range(bound[k])
        dqm.set_linear('x' + str(k), lagrange * (weights[k] ** 2) * (np.array(pieces) ** 2) - values[k] * pieces)

    # # Hamiltonian xi-xj terms
    for i in range(x_size):
        for j in range(i + 1, x_size):
            biases_dict = {}
            for piece1 in range(bound[i]):
                for piece2 in range(bound[j]):
                    biases_dict[(piece1, piece2)] = (2 * lagrange * weights[i] * weights[j]) * piece1 * piece2

            dqm.set_quadratic('x' + str(i), 'x' + str(j), biases_dict)

    # Hamiltonian y-y terms
    for k in range(num_slack_variables):
        dqm.set_linear('y' + str(k), lagrange * np.array([0, 1]) * (y[k] ** 2))

    # Hamiltonian yi-yj terms
    for i in range(num_slack_variables):
        for j in range(i + 1, num_slack_variables):
            dqm.set_quadratic('y' + str(i), 'y' + str(j), {(1, 1): 2 * lagrange * y[i] * y[j]})

    # Hamiltonian x-y terms
    for i in range(x_size):
        for j in range(num_slack_variables):
            biases_dict = {}
            for piece1 in range(bound[i]):
                biases_dict[(piece1, 1)] = -2 * lagrange * weights[i] * y[j] * piece1

            dqm.set_quadratic('x' + str(i), 'y' + str(j), biases_dict)

    return dqm, x

# Without the Andrew Lucas log trick
def build_knapsack_dqm_variablebound(values, weights, weight_capacity, bound, verbose=False):
    """Construct DQM for the generalized knapsack problem
    Args:
        values (array-like):
            Array of values associated with the items
        weights (array-like):
            Array of weights associated with the items
        weight_capacity (int):
            Maximum allowable weight
        bound(array-like):
            Maximum allowable pieces for each item
    Returns:
        Discrete quadratic model instance
        x: varibles
    """
    bound = [b + 1 for b in bound]  # also take into account the value 0

    # Lagrange multipliers A>max(values)>0
    A1 = max(values) * 8
    A2 = max(values) * 2

    num_of_items = len(values)
    ##@  Discrete Quadratic Model @##
    dqm = DiscreteQuadraticModel()

    x = []
    # @ Add variables @##
    for k in range(num_of_items):
        x.append(dqm.add_variable(bound[k], label='x' + str(k)))  # number of discrete values

    for n in range(1, weight_capacity + 1):
        dqm.add_variable(2, label='y' + str(n))  # either 0 or 1, 2 values possible

    ##@ Hamiltonian xi-xi terms ##
    for k in range(num_of_items):
        pieces = range(bound[k])
        #     dqm.set_linear('x' + str(k),  - values[k]*pieces)
        dqm.set_linear('x' + str(k), A2 * (weights[k] ** 2) * (np.array(pieces) ** 2) - values[k] * np.array(pieces))

    # Hamiltonian y-y terms
    for n in range(1, weight_capacity + 1):
        dqm.set_linear('y' + str(n), np.array([0, 1]) * (n ** 2 * A2 - A1))

    # Hamiltonian yi-yj terms
    for n in range(1, weight_capacity + 1):
        for m in range(n + 1, weight_capacity + 1):
            dqm.set_quadratic('y' + str(n), 'y' + str(m), {(1, 1): 2 * A1 * (1 + m * n)})

    # # Hamiltonian xi-xj terms
    for i in range(num_of_items):
        for j in range(i + 1, num_of_items):
            biases_dict = {}
            for piece1 in range(bound[i]):
                for piece2 in range(bound[j]):
                    biases_dict[(piece1, piece2)] = (2 * A2 * weights[i] * weights[j]) * piece1 * piece2
            dqm.set_quadratic('x' + str(i), 'x' + str(j), biases_dict)

    # Hamiltonian x-y terms
    for i in range(num_of_items):
        for n in range(1, weight_capacity + 1):
            biases_dict = {}
            for piece1 in range(bound[i]):
                biases_dict[(piece1, 1)] = -2 * A2 * weights[i] * n * piece1

            dqm.set_quadratic('x' + str(i), 'y' + str(n), biases_dict)

    return dqm, x

**Comment by ACE07-Sev** [comment]
Please assist me on confirming this ASAP

**Comment by arcondello** [comment]
> Does cqm = ConstrainedQuadraticModel.from_dqm(dqm) correctly create the CQM equivalent of an existing DQM with fixed and/or varying bounds?

`ConstrainedQuadraticModel.from_dqm()` does correctly create a CQM from a DQM as stated in the docs. I do not understand the question about fixed and/or varying bounds.
