### ISSUE TITLE
PyPy3.8 compilation fails with error: too many initializers

### ISSUE THREAD

**Issue by BastianZim** [dwavesystems/dimod#1169]
**Description**
A clear and concise description of the bug.

When compiling for [Linux, win, osx] PyPy3.8 the process fails with `dimod/binary/cybqm/base.cpp:2110:1: error: too many initializers for 'PyTypeObject' {aka '_typeobject'}
`
**Steps To Reproduce**

Build the package using `python -m pip install . -vv`

**Expected Behavior**

Build succeeds

**Environment**
 - OS: [Linux, win, osx]
 - Python version: PyPy3.8

**Additional Context**
Add any other background information about the problem.

This is for the conda-forge distribution. I understand that supporting PyPy3.8 is maybe not in your scope so please feel free to close this issue if that's the case.

PR: https://github.com/conda-forge/dimod-feedstock/pull/5
Logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=489981&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412&l=434

**Comment by BastianZim** [comment]
Awesome, thank you @arcondello 
3.9 is working so no problem for me to just restrict it to that, in case it's a lot of work for you.

**Comment by arcondello** [comment]
Hi @BastianZim, no luck. I think for now our official answer will have to be that we still don't support PyPy. If you want to add unofficial support for 3.9 that's fine with us :smile:

**Comment by arcondello** [comment]
Though I do see [NumPy supports PyPy3.8](https://pypi.org/project/numpy/1.22.3/#files). I cannot really find an official support policy other than a few issues (e.g. https://github.com/numpy/numpy/pull/20528).

If they had an official policy, we could consider following them. I just don't want to have to be checking every month to see what wheels they do and don't build.

Let's keep this issue open for now though, and we can revisit in a few months maybe.

**Comment by arcondello** [comment]
Ok, was able to fix it, all you need to do is update Cython (see https://github.com/scipy/scipy/issues/15429). I'll update the Cython version in `requirements.txt` and `pyproject.toml`

**Comment by arcondello** [comment]
For what it's worth, I don't think dimod in pypy is a great idea. Running the last example in the recently adding scaling guide (#1172) gives an almost 10x slowdown. There are of course cases that pypy also performs well.

**Comment by BastianZim** [comment]
Hi @arcondello thanks for investigating this and sorry for the late reply, I was on holiday. Great, then I'll enable this once the new version is released.

> For what it's worth, I don't think dimod in pypy is a great idea.

Agreed. Conda-forge just compiles every package to pypy as well just to offer it but I don't recommend using it.
