### ISSUE TITLE
Adding constraints to CQM

### ISSUE THREAD

**Issue by ACE07-Sev** [dwavesystems/dimod#1171]
I'm trying to use CQM for an optimization problem and have basically formulated my model using two segments :
1) Objective
2) Constraint

I created a BQM to model the objective and basically just set that as the objective of the CQM. This works well, however when I add the constraints (which I created by creating QMs and adding them as constraints with a rhs to the CQM) it doesn't take the constraint into effect and just minimizes the objective with no regards to the constraint.
this is my code :
https://github.com/ACE07-Sev/CQM/blob/7b4c17ae325ba4a2326a76a7350c1bcec84535c5/CQM.py

I get the following wrong input :
The universe is [0, 2, 5, 6, 7, 8, 9]
Number of elements in the universe: 7
There are 5 collections: [{2, 5, 6, 7, 8}, {0, 9, 5, 7}, {0, 5, 6, 7}, {0, 5, 7}, {2, 5, 6, 8, 9}]
Number of sets: N=5
x_1 x_2 x_3 x_4 x_5 y_(1, 1) y_(1, 2) ... y_(7, 5) energy num_oc. ...
18 0.0 0.0 0.0 0.0 0.0 1.0 0.0 ... 0.0 0.0 1 ...
27 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 1 ...
32 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 1 ...
33 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 1 ...
34 0.0 0.0 0.0 0.0 0.0 1.0 0.0 ... 0.0 0.0 1 ...
36 0.0 0.0 0.0 0.0 0.0 1.0 0.0 ... 0.0 0.0 1 ...
37 0.0 0.0 0.0 0.0 0.0 1.0 0.0 ... 0.0 0.0 1 ...
50 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 1 ...
51 0.0 0.0 0.0 0.0 0.0 1.0 0.0 ... 0.0 0.0 1 ...
2 0.0 0.0 1.0 0.0 0.0 1.0 0.0 ... 0.0 1.0 1 ...
16 0.0 0.0 1.0 0.0 0.0 1.0 1.0 ... 0.0 1.0 1 ...
17 0.0 0.0 0.0 0.0 1.0 0.0 0.0 ... 0.0 1.0 1 ...
19 0.0 0.0 0.0 0.0 1.0 1.0 0.0 ... 0.0 1.0 1 ...
20 1.0 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 1.0 1 ...
21 0.0 1.0 0.0 0.0 0.0 1.0 1.0 ... 0.0 1.0 1 ...
22 0.0 0.0 1.0 0.0 0.0 0.0 0.0 ... 0.0 1.0 1 ...
23 1.0 0.0 0.0 0.0 0.0 1.0 1.0 ... 0.0 1.0 1 ...
24 0.0 0.0 0.0 0.0 1.0 0.0 0.0 ... 0.0 1.0 1 ...
25 0.0 0.0 0.0 0.0 1.0 1.0 0.0 ... 0.0 1.0 1 ...
26 0.0 1.0 0.0 0.0 0.0 1.0 0.0 ... 0.0 1.0 1 ...
28 0.0 0.0 0.0 1.0 0.0 0.0 0.0 ... 0.0 1.0 1 ...
29 1.0 0.0 0.0 0.0 0.0 0.0 1.0 ... 0.0 1.0 1 ...
30 0.0 0.0 0.0 0.0 1.0 0.0 0.0 ... 0.0 1.0 1 ...
31 0.0 0.0 1.0 0.0 0.0 1.0 0.0 ... 0.0 1.0 1 ...
35 0.0 0.0 1.0 0.0 0.0 1.0 0.0 ... 0.0 1.0 1 ...
38 0.0 0.0 1.0 0.0 0.0 0.0 1.0 ... 0.0 1.0 1 ...
39 0.0 0.0 1.0 0.0 0.0 1.0 0.0 ... 0.0 1.0 1 ...
40 0.0 0.0 0.0 0.0 1.0 0.0 0.0 ... 0.0 1.0 1 ...
41 0.0 0.0 0.0 0.0 1.0 1.0 0.0 ... 0.0 1.0 1 ...
43 0.0 0.0 0.0 0.0 1.0 0.0 0.0 ... 0.0 1.0 1 ...
46 0.0 0.0 1.0 0.0 0.0 0.0 0.0 ... 0.0 1.0 1 ...
47 0.0 1.0 0.0 0.0 0.0 1.0 0.0 ... 0.0 1.0 1 ...
49 0.0 0.0 1.0 0.0 0.0 0.0 0.0 ... 0.0 1.0 1 ...
3 0.0 0.0 1.0 0.0 1.0 1.0 0.0 ... 0.0 2.0 1 ...
6 1.0 0.0 0.0 0.0 1.0 1.0 0.0 ... 0.0 2.0 1 ...
7 0.0 0.0 1.0 0.0 1.0 0.0 1.0 ... 0.0 2.0 1 ...
44 1.0 0.0 0.0 0.0 1.0 1.0 0.0 ... 0.0 2.0 1 ...
45 0.0 0.0 1.0 0.0 1.0 1.0 0.0 ... 0.0 2.0 1 ...
48 0.0 0.0 1.0 0.0 1.0 1.0 0.0 ... 0.0 2.0 1 ...
52 0.0 0.0 1.0 0.0 1.0 1.0 0.0 ... 0.0 2.0 1 ...
0 1.0 0.0 1.0 0.0 1.0 1.0 0.0 ... 0.0 3.0 1 ...
1 1.0 0.0 1.0 0.0 1.0 1.0 0.0 ... 0.0 3.0 1 ...
9 0.0 1.0 1.0 1.0 0.0 0.0 0.0 ... 0.0 3.0 1 ...
11 1.0 0.0 1.0 0.0 1.0 1.0 1.0 ... 0.0 3.0 1 ...
14 1.0 1.0 0.0 0.0 1.0 1.0 0.0 ... 0.0 3.0 1 ...
15 1.0 0.0 1.0 0.0 1.0 1.0 0.0 ... 0.0 3.0 1 ...
42 1.0 0.0 1.0 0.0 1.0 1.0 0.0 ... 0.0 3.0 1 ...
4 1.0 1.0 1.0 0.0 1.0 0.0 1.0 ... 0.0 4.0 1 ...
5 1.0 1.0 1.0 0.0 1.0 0.0 0.0 ... 0.0 4.0 1 ...
8 1.0 1.0 0.0 1.0 1.0 0.0 0.0 ... 1.0 4.0 1 ...
10 1.0 1.0 1.0 0.0 1.0 0.0 0.0 ... 0.0 4.0 1 ...
12 1.0 1.0 1.0 0.0 1.0 0.0 0.0 ... 0.0 4.0 1 ...
13 1.0 1.0 1.0 0.0 1.0 0.0 0.0 ... 0.0 4.0 1 ...
['INTEGER', 53 rows, 53 samples, 40 variables]

there should at least be one x_i equal to 1 so we are using at least one subset to cover the U list, but it completely ignores the constraint and just minimizes it by using no subsets. 

Is the issue from me implementing the constraints wrong (is there another form I should use to add constraints? I use this form as my approach to implement constraints : https://github.com/dwavesystems/dimod/issues/1165

how can I resolve this so that the model actually takes the constraint into effect when running?

 P.S this is a code question as my mathematics has checked out, and am purely asking about the code, which I assume this issue is under logical error of not adding constraints right(otherwise it should be working).

Please do not close this as I have seen many issues regarding adding constraints to CQM model and none have been answered fully. Thank you.

**Comment by arcondello** [comment]
Hi @ACE07-Sev, 

I suggest that you try [filtering](https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/generated/dimod.SampleSet.filter.html#dimod.SampleSet.filter) by feasible solutions:
```python
print(sampleset.filter(lambda d: d.is_feasible))
```

I am now going to close this issue because it is a debugging question and therefore not [on topic](https://stackoverflow.com/help/on-topic). I am going to again direct you to our [Leap community](https://support.dwavesys.com/hc/en-us/community/topics) for this sort of question in the future.
