### ISSUE TITLE
CQM Objective energy in sampleset showing all zero

### ISSUE THREAD

**Issue by ACE07-Sev** [dwavesystems/dimod#1205]
greetings,

I've written a script for a CQM for the TSP problem, and wish to know why the energy of each sample is zero. This is my code :
https://github.com/ACE07-Sev/CQM-TSP/blob/main/CQM_TSP.py

and this is the sampleset I get :
   X_1_2 X_1_3 X_1_4 X_1_5 X_2_1 X_2_3 X_2_4 X_2_5 X_3_1 X_3_2 X_3_4 X_3_5 X_4_1 X_4_2 X_4_3 X_4_5 X_5_1 X_5_2 X_5_3 X_5_4 energy num_oc. is_sat. is_fea.
0    0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
1    0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
2    1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0    0.0       1 arra...    True
3    0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
4    1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
5    0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
6    0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0    0.0       1 arra...    True
7    1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
8    1.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0    0.0       1 arra...    True
9    1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   1.0    0.0       1 arra...    True
10   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0    0.0       1 arra...    True
11   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0    0.0       1 arra...    True
12   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
13   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
14   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
15   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
16   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   1.0    0.0       1 arra...    True
17   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0    0.0       1 arra...    True
18   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0    0.0       1 arra...    True
19   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
20   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
21   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
22   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
23   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0    0.0       1 arra...    True
24   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
25   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
26   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
27   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0    0.0       1 arra...    True
28   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0    0.0       1 arra...    True
29   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
30   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0    0.0       1 arra...    True
31   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0    0.0       1 arra...    True
32   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0    0.0       1 arra...    True
33   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
34   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
35   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
36   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
37   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0    0.0       1 arra...    True
38   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0    0.0       1 arra...    True
39   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
40   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
41   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
42   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
43   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
44   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True
45   1.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0    0.0       1 arra...    True
46   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0    0.0       1 arra...    True
47   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0    0.0       1 arra...    True

P.S the reason I am getting subtours is because I still haven't added the subtour elimination constraint, currently just wish to know why the energy for each sample is 0

My test input is as follows :
Input x coordinate
1
Input y coordinate
1
Input x coordinate
2
Input y coordinate
3
Input x coordinate
3
Input y coordinate
2
Input x coordinate
2
Input y coordinate
4
Input x coordinate
1
Input y coordinate
5

**Comment by ACE07-Sev** [comment]
Update : I have added the subtour elimination constraint (DFJ formulation), and tested the model for getting a global cycle. The only issue left is just the energy being 0 for all samples.

**Comment by arcondello** [comment]
[As before](https://github.com/dwavesystems/dimod/issues/1168#issuecomment-1099458771), I'd recommend reaching out to our [Leap community](https://support.dwavesys.com/hc/en-us/community/topics).
