### ISSUE TITLE
CQM Objective having 0 energy for all samples

### ISSUE THREAD

**Issue by ACE07-Sev** [dwavesystems/dimod#1214]
Hi, I've written a script for a TSP model, and weirdly all the energies for the samples are 0. Could you kindly assist with this?
my code is in my repo :
https://github.com/ACE07-Sev/CQM-TSP

If you could kindly assist me in resolving this I'd be immensely grateful. (it's a bit urgent hence I would be immensely grateful if you could help me solve this as soon as possible. Thank you so much for the support)

**Comment by arcondello** [comment]
[As before](https://github.com/dwavesystems/dimod/issues/1168#issuecomment-1099458771), I'd recommend reaching out to our [Leap community](https://support.dwavesys.com/hc/en-us/community/topics).
