### ISSUE TITLE
Documentation talks about the C++ interface but there are no C++ files in this repository

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dimod#1237]
**Description**
Documentation is [here](https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/cpp.html).

**Environment**
 - OS: FreeBSD 13.1
 - Python version: 3.9

**Comment by arcondello** [comment]
It's header-only, and can be found [here](https://github.com/dwavesystems/dimod/tree/main/dimod/include/dimod). Note that we are expecting significant changes to the API for dimod 0.12.0, releasing later this fall.

**Comment by yurivict** [comment]
Thank you.
