### ISSUE TITLE
Please use $(CXX) instead of g++ in makefiles

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dimod#1239]
**Description**
[Here](https://github.com/dwavesystems/dimod/blob/main/testscpp/Makefile#L20) and everywhere.

```$(CXX)``` is a standard variable for a C++ compiler, and ```g++``` is one of compilers.
On BSDs C++ compiler executable has the name ```c++```..

**Comment by arcondello** [comment]
Good idea
