### ISSUE TITLE
Tests succeed but with many assertions

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dimod#1241]
**Description**
```
./test_main
===============================================================================
All tests passed (104141 assertions in 24 test cases)
```

Assertions are usually bad, but tests are still succeeding? This looks strange, no?

Version: 0.11.5
clang-14
FreeBSD 13.1

**Comment by arcondello** [comment]
I am not sure what you mean? We include many asserts in the code for debugging purposes. But when we compile the libraries for the Python interface we use `-DNDEBUG` to disable them.

We leave them enabled for testing as well.

**Comment by arcondello** [comment]
Scratch that, I believe this is just counting the number of [Assertion Macros](https://github.com/catchorg/Catch2/blob/devel/docs/assertions.md) that succeeded in the test cases.

**Comment by yurivict** [comment]
It looks like catch2 is printing this confusing message.

Thanks.
