### ISSUE TITLE
[question] Why SampleSet.first has type Sample and when SampleSet is iterated individual objects have a different type SampleView?

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dimod#1244]
**Description**
If the 'first' item in SampleSet is Sample, shouldn't all objects returned by the iteration of SampleSet have the same type?

Sample prints sample vector, energy and other fields, but SampleView for some reason only prints sample vector.

**Comment by arcondello** [comment]
I agree ideally they would be consistent. Support for `for sample in sampleset: ...` is old and returns only the samples themselves for legacy/backwards compatibility reasons. `.first` returns the actual contents of the sample set. We generally encourage users to use
```python
for sample in sampleset.samples():
    ...
```
or
```python
for datum in sampleset.data():
    ...
```
which are more explicit. `.first` returns the first value of that latter.

**Comment by yurivict** [comment]
```sampleset.samples()``` returns the list of SampleView objects.
```sampleset.data()``` returns the list of Sample objects which have more information.

Thank you for your answer.
