### ISSUE TITLE
Adding a bad soft constraint adds a bad constraint to the CQM

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#1261]
**Description**
CQM does not allow a quadratic penalty on non-binary variables. But when you try that, a fake constraint is added 

**Steps To Reproduce**
```
>>> cqm1 = dimod.ConstrainedQuadraticModel()
>>> cqm1.add_constraint(a <= 3, weight=55, penalty="quadratic", label="Fake constraint")
ValueError
>>> cqm1.constraints
{'Fake constraint': Le(QuadraticModel({'a': 1.0}, {}, 0.0, {'a': 'INTEGER'}, dtype='float64'), 3)}
```

**Expected Behavior**
The rejection of the unsupported constraint should prevent the constraint from being added to the model

**Environment**
 - OS: WIN 10 
 - Python version: 3.10.2

**Comment by arcondello** [comment]
Closed by https://github.com/dwavesystems/dimod/pull/1270
