### ISSUE TITLE
TypeError: '<=' not supported between instances of 'QuadraticModel' and 'BinaryQuadraticModel'

### ISSUE THREAD

**Issue by ACE07-Sev** [dwavesystems/dimod#1355]
**Description**
I am trying to implement the Gavish-Graves subtour elimination constraint for a CQM. To do so, I have to implement this CPLEX code [1] using Dimod :
```
for i in nodes:
    if i >= 2:
        model.add_constraint(
            model.sum(z[i, j] for j in nodes) - model.sum(z[j, i] for j in nodes if j != 1) == 1
        )
        
for i in nodes:
    for j in nodes:
        if i != 1:
            model.add_constraint(z[i, j] <= (nbnode - 1) * y[i, j])
```
Where y is the binary variable representing the edge connection from i to j, and Z is a positive number. 

**Steps To Reproduce**
```
# Number of nodes
n = 6

# Initializing the CQM
cqm = ConstrainedQuadraticModel()

# Initializing the decision var
X = np.array([[Binary(f"X_{i+1}_{j+1}") if i!=j else 0 for j in range(n)] for i in range(n)])

# Initializing the decision var
Z = np.array([[Real(f"Z_{i+1}_{j+1}") if i!=j else 0 for j in range(n)] for i in range(n)])

for i in range(n):
    if i >= 1:
        constraint_3 = quicksum(Z[i][j] for j in range(n)) - quicksum(Z[i][j] for j in range(n) if j != 0)
        cqm.add_constraint(constraint_3 == 1, label="Constraint 3-" + str(i+1))

for i in range(n):
    for j in range(n):
        if i != 0:
            cqm.add_constraint(Z[i][j] <= (n - 1) * X[i][j], label="Constraint 4-" + str(i+1) + str(j+1))
```

**Expected Behavior**
I am expecting to have it pass similar to the CPLEX code.

**Environment**
 - Python version: [3.11]

**Additional Context**
Here is the paper which I took the CPLEX code from : 
[1] : https://www.mdpi.com/2075-1680/10/1/19

Kindly let me know if you would like the full code for this to have it run in full.

**Comment by ACE07-Sev** [comment]
I tried #1211 mindset, and thought something like : 

$(n-1) * X[i][j] / Z[i][j] >= 1$, and got this error : 

```
TypeError: unsupported operand type(s) for /: 'int' and 'QuadraticModel'
```

Here is my code for it : 
```
for i in range(n):
    for j in range(n):
        if i != 0:
            cqm.add_constraint((n - 1) * X[i][j]/Z[i][j] >= 1, label="Constraint 4-" + str(i+1) + str(j+1))
```

I imagine the case for multiplication is quite different from addition, I will keep looking in the open and closed issues in case it has been addressed before.

**Comment by arcondello** [comment]
> I resolved the issue for now, I'll address this again in case I have any missed issues.

Sounds good, closing for now.
