### ISSUE TITLE
data_vectors should have either numpy array values, or a list values, but not both.

### ISSUE THREAD

**Issue by orenshk** [dwavesystems/dimod#172]
https://github.com/dwavesystems/dimod/blob/7b75e47ce4fec541e432f84367ba58393934b941/dimod/response.py#L40

Making it be more than one thing requires the parser of the response to inspect the object before using it. If we want to have the benefits of a numpy array for some of the data_vectors, I think it's worth it to make everything a numpy array

If we don't need it to be a numpy array, might as well make them all lists?

**Comment by arcondello** [comment]
For reference, on python 3.6.3

```
import timeit
import numpy as np

length = 1000

class MyObj(object):
    pass

test_list = [MyObj() for __ in range(length)]
test_array = np.asarray(test_list, dtype=object)
```

```
In [9]: % timeit test_list[500]
30.9 ns ± 0.296 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [10]: % timeit test_array[500]
52.5 ns ± 0.333 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
