### ISSUE TITLE
Embedding/majority_vote unexpected behavior for even chains

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#178]
Half of chains will have even numbers of nodes. For even chains with no majority value, collections.Counter.most_common() is defined as "Elements with equal counts are ordered arbitrarily". 
I would not expect that from a majority_vote policy, just from the weighted_random policy -- to me it seems better to discard in such case. If not, this should be prominently noted (I did that as a workaround for the meanwhile) 

>>> embedding = {'a': {0, 1}, 'b': ...
>>> samples = {0: 1, 1: 0, 2: ...
>>> next(dimod.embedding.majority_vote(samples, embedding ...
{'a': 0, '

**Comment by arcondello** [comment]
It should be noted. Discarding those chains would have no use for the user. They are not trying to get statistics on the most common value, they are trying to resolve broken chains.

**Comment by JoelPasvolsky** [comment]
I noted it in the embedding doc work that will be a PR later this morning.
Thanks,
Joel
