### ISSUE TITLE
Embedding/weight_random failing: NameError: global name 'random' is not defined

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#179]
It works only if I change line 160 in chain_breaks.py from "unembedded[v] = random.choice(vals)" to "unembedded[v] = np.random.choice(vals)"

In [284]: next(dimod.embedding.weighted_random(sample, embedding))
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-284-c5974cb75d13> in <module>()
----> 1 next(dimod.embedding.weighted_random(sample, embedding))

C:\Users\jpasvolsky\!git_DocsOS\env\ADTT\dimod\dimod\embedding\chain_breaks.pyc in weighted_random(sample, embedding)
    124     for v, chain in iteritems(embedding):
    125         vals = [sample[u] for u in chain]
--> 126
    127         if _all_equal(vals):
    128             unembedded[v] = vals.pop()

NameError: global name 'random' is not defined

**Comment by arcondello** [comment]
Great! I think your fix should be a PR

**Comment by JoelPasvolsky** [comment]
PR 180.
