### ISSUE TITLE
BinaryQuadraticModel.relabel_variables

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#191]
This is the only transformation method that returns a value, the others do not. They should all be consistent one way or the other.

>>> bqm = dimod.BinaryQuadraticModel({1: 1, 2: 2}, {(1, 2): 0.5}, 0.5, dimod.SPIN)
>>> bqm.flip_variable(1)

>>> bqm = dimod.BinaryQuadraticModel({1: 1, 2: 2}, {(1, 2): 0.5}, 0.5, dimod.SPIN)
>>> bqm.relabel_variables({1: 'a'})
Out[149]: BinaryQuadraticModel({...

**Comment by JoelPasvolsky** [comment]
Also, having the spontaneous output means a doctest failure unless I add a #skip doctest:

Document: reference/generated/dimod.BinaryQuadraticModel.relabel_variables
--------------------------------------------------------------------------
**********************************************************************
File "reference\generated\dimod.BinaryQuadraticModel.relabel_variables.rst", line ?, in default
Failed example:
    model.relabel_variables({0: 'a'})
Expected nothing
Got:
    BinaryQuadraticModel({1: 1.0, 'a': 0.0}, {('a', 1): -1}, 0.0, Vartype.SPIN)
**********************************************************************
1 items had failures:

**Comment by arcondello** [comment]
I think it is important to have a consistent return value and we want both inplace and copy versions of this function.
