### ISSUE TITLE
SpinReversalTransformComposite() fails for non-labeled BQM

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#193]
code line ```tf_idxs = [flipped_response.label_to_idx[v] for v in flipped_response.variable_labels]``` in spin_transform.py fails for BQMs that use index instead of labels:

Works:
response = dimod.StructureComposite(dimod.ExactSolver(),
     ...:                  ['a', 'b'], [('a', 'b')]).sample_ising({'a': 1, 'b': 1}, {})

Fails:
response = dimod.StructureComposite(dimod.ExactSolver(),
     ...:                  [0, 1], [(0, 1)]).sample_ising({0: 1, 1: 1}, {})

because 

```if variable_labels is None:
            self.variable_labels = None
            self.label_to_idx = None```

so 

```tf_idxs = [flipped_response.label_to_idx[v] for v in flipped_response.variable_labels]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-9467e9b7c7f4> in <module>()
----> 1 tf_idxs = [flipped_response.label_to_idx[v] for v in flipped_response.variable_labels]

TypeError: 'NoneType' object is not iterable```

**Comment by arcondello** [comment]
Closed by #417
