### ISSUE TITLE
histogram mode is not working

### ISSUE THREAD

**Issue by conta877** [dwavesystems/dimod#211]
```
h = 0:-1,4:-1}
J = {(0,4):-1} 
solution = solver.sample_ising(h,J,num_reads=1000,answer_mode='histogram')
print len(solution.data_vectors['num_occurrences'])
```
returns 1000

looking at the samples, there is a single unique sample [1,1] as expected. Since we are asking for histogram mode, there should be a single entry for sample,energy,num_occurrences with num_occurrences = 1000, energy = -3.0 sample = {0:1,4:1}.
instead of 
1000 x {num_occurrences = 1, energy = -3.0, sample = {0:1,4:1} 

so above code block should return 1.

**Comment by randomir** [comment]
Just to confirm, this is a bug in dimod, since cloud client returns the correct result (one sample with num_occurrences = 1000).
