### ISSUE TITLE
Response futures appear to be strings?

### ISSUE THREAD

**Issue by frechette-alex** [dwavesystems/dimod#217]
```
from dwave.system.samplers import DWaveSampler

sampler = DWaveSampler(profile='BAY4')

h = {}
J = {(0, 4): -1}

response = sampler.sample_ising(h, J, num_reads=10)
print response.done()
```
yields
```
AttributeError: 'str' object has no attribute 'done'
```
If I print `response._futures` right after creating the response, I get 
```
{'ignore_extra_keys': True, 'samples_key': 'samples', 'futures': (<dwave.cloud.computation.Future object at 0x7f31793d8110>,), 'data_vector_keys': {'energies': 'energy', 'num_occurrences': 'num_occurrences'}, 'active_variables': [0, 4], 'variable_labels': [0, 4], 'info_keys': {'timing': 'timing'}}
```
Is it possible `response._futures` is temporarily overwritten somewhere? Apparently yes, `response._futures` can hold something else than futures: at https://github.com/dwavesystems/dimod/blob/master/dimod/response.py#L561, it gets populated with a bunch of stuff, including non-futures.

So `response._futures` can be different things at different stages of the response ... :-1:

**Comment by arcondello** [comment]
This is a bug in the `.done()` syntax. Will fix.
