### ISSUE TITLE
enum34 breaks working Anaconda installations

### ISSUE THREAD

**Issue by peterwittek** [dwavesystems/dimod#227]
The requirement enum34 is actually unnecessary and its use is discouraged: it breaks random things. For instance, on Anaconda, it breaks spelling completion in Spyder.

**Comment by arcondello** [comment]
Hi peterwittek,

We use enum as a backport for python before 3.3. We can add filter so that it is only installed for legacy versions.

**Comment by peterwittek** [comment]
Thank you.
