### ISSUE TITLE
Mention `num_occurrences` in docs for `dimod.Response`

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#228]
It's not clear from the docs how to get `num_occurrences`, alongside list of samples.

User's [comment here](https://support.dwavesys.com/hc/en-us/community/posts/360013878673/comments/360001418813).

**Comment by arcondello** [comment]
`num_occurrences` is a sampler-specific data field, not in general for dimod Samplers. We could consider making is a required data field as it has come up in multiple cases.

**Comment by randomir** [comment]
Adding something like this to [`dimod.Response`](http://dimod.readthedocs.io/en/latest/reference/response.html) docs would also help:

```
>>> list(response.data())
[Sample(sample={0: -1}, num_occurrences=52, energy=0.0),
 Sample(sample={0: 1}, num_occurrences=48, energy=0.0)]
```

**Comment by wbernoudy** [comment]
@randomir @arcondello 
Should we make `num_occurrences` required for the next backwards compatibility update?

I see the arguments as follows. Making it optional means more flexibility for wrapping solvers and less overhead (no need to compute the histogram). The downside is less uniformity in the responses from different samplers, and that `len(response)` may or may not be equal to the `num_samples`/`num_reads` parameter. One other downside I can think of is that if it is required, the samples returned lose their "time-dependence" which I can see being important for the QPU and maybe other solvers.

While it would be possible to require `num_occurrences` and then allow the samples to be non-unique (so you could take your existing sampler, and just set `num_occurrences=1` for every returned sample), I would argue this will be too confusing as the name and current usage in the ecosystem implies that what's returned is a proper histogram. 

I think the best solution is to make `num_occurrences` required, and to provide a decorator which builds the histogram if the user needs it when making a sampler.

This is perhaps tangential, but I think we should also consider standardizing the `num_samples`/`num_reads` parameter. I understand that this parameter does not apply for some solvers, and so should remain optional, but it's such a common parameter that I think there should be just one way to do it. Maybe this just means stating this in the docs for how to make a sampler (i.e. "If your sampler takes an argument that specifies how many samples to return, use `num_reads`"). Another option could be to have another ABC that requires `num_reads`.

**Comment by randomir** [comment]
And while we're on topic of long-term planning/breaking compat/renaming stuff -- why not call that property simply `histogram`?

:+1: for standardizing names across API (I believe `num_reads` is inherited from SAPI/QS).

The need for pre/post-processing of parameters/responses from SAPI has already come up several times (e.g. here: https://github.com/dwavesystems/dwave-cloud-client/issues/199), and that seems to be the direction which makes most sense (in terms of API flexibility, unification and faster development).

**Comment by arcondello** [comment]
Made required in #243 .

I agree we should standardise `num_reads`/`num_samples`. I think by dint of longevity `num_reads` is the winner.
