### ISSUE TITLE
`Response.from_futures` parameter `info_keys` is unnecessarily inconvenient and inconsistent

### ISSUE THREAD

**Issue by wbernoudy** [dwavesystems/dimod#237]
https://github.com/dwavesystems/dimod/blob/3b4243f81cf0c6d9c1e66dae5f9ea75d4a438d48/dimod/response.py#L442

Currently, the `info_keys` parameter requires you to know which which keys in the return value from your future will correspond to which keys in the `Response.info` dict. This is quite inconvenient if you are writing code that is intended to be agnostic to an underlying sampler, as you may not know what "format" the sampler will return for information about the samples. Furthermore, this parameter is inconsistent with `Response.from_dicts`, which simply accepts a `info` parameter.

Proposed solution: change `info_keys=None` to `info_key="info"`, such that when the future returns, dimod will simply take the value of `future.result[info_key]` (if it exists) and stick it into the info of the newly created `Response`.

**Comment by arcondello** [comment]
I think this might duplicate #127 ?

**Comment by arcondello** [comment]
Also, I am trying to fit a refactor of the response object construction in the next week or so, so this is timely.

**Comment by wbernoudy** [comment]
Yes, but I like my solution slightly more :)

**Comment by arcondello** [comment]
Can you write a short example of the syntax you have in mind?

**Comment by wbernoudy** [comment]
```python
def async_sampler(...):
    ...
    return {
        "samples": ...,
       "energy": ...,
       "custom_info": {"some": "info"},
    }

executor = ThreadPoolExecutor()
fut = executor.submit(async_sampler, some, args)
response = dimod.Response.from_futures((fut,), dimod.BINARY, num_vars, info_key="custom_info")
response.info # => {"some": "info"}
```

**Comment by wbernoudy** [comment]
@arcondello just brought to my attention that this syntax will incur significant pain for the wrappers of some samplers due to the nature of needing to modify the futures themselves if they do not return a dict with a neatly packaged `"info"` key.

New proposal: optional `result_coercer` argument which takes a function. This function should "coerce" whatever the future returns into a dict which has the keys `"samples"`, `"energy"`, and `"info"`. By default, `result_coercer=lambda r: {k: r.get(k, None) for k in ("samples", "energy", "info")}` or similar.

```python
def async_sampler(...):
    ...
    return {
        "samples": ...,
        "energy": ...,
        "info": {"some", "info"},
        "custom_info": {"custom": "info"},
    }

executor = ThreadPoolExecutor()
fut = executor.submit(async_sampler, some, args)
response0 = dimod.Response.from_futures((fut,), dimod.BINARY, num_vars)
response0.info # => {"some": "info"}
response1 = dimod.Response.from_futures(
    (fut,), dimod.BINARY, num_vars, 
    result_coercer=lamdba r: {"samples": r["samples"], "energies": r["energies"], "info": r["custom_info"]}
)
response1.info # => {"custom": "info"}
```

As @arcondello also realized, this allows you to do fun things like change the vartype or anything else of the result returned by the future.

**Comment by arcondello** [comment]
As much as I like `result_coercer` probably is should be called `result_hook` or the like
