### ISSUE TITLE
Allow user-specified mapping type for `BinaryQuadraticModel`s

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#238]
```
bqm = dimod.BinaryQuadraticModel(linear, quadratic, offset, vartype, mapping_type=OrderedDict)
```
This would affect `.linear` and `.quadratic`, possibly `.adj` as well.

**Comment by arcondello** [comment]
Or, even to create an `OrderedBinaryQuadraticModel` subclass a la https://networkx.github.io/documentation/stable/reference/classes/ordered.html

**Comment by randomir** [comment]
I like the subclass approach too. And it looks like one would have to override just `__init__`, because `linear` and `quadratic` are initialized only there.

Hooks approach would make more sense in case instances of the mapping are created on the fly, not just once.

**Comment by arcondello** [comment]
OrderedBQMs were removed in #323 but it seems there might still be a use case for them.

**Comment by arcondello** [comment]
Creating a new issue #397
