### ISSUE TITLE
Embedding QUBO leads to out-of-range linear terms.

### ISSUE THREAD

**Issue by jking-ca** [dwavesystems/dimod#241]
If I determine the correct scaling factor to scale a QUBO such that the Ising form fits in the QPU range, I should be able to scale the QUBO by this amount, embed it, and solve the Ising.  However, the embedding causes some linear QUBO terms to be out of range in the resulting Ising model.  As discussed with @arcondello.

https://github.com/dwavesystems/dimod/blob/8ebfffa42319aa4850cfc5a1c99a8711eac44722/dimod/embedding/transforms.py#L125

**Comment by arcondello** [comment]
Example case:
```
        bqm = dimod.BinaryQuadraticModel.from_ising({}, {(0, 1): 1, (1, 2): 1, (0, 2): 1})

        # convert to BINARY
        bqm.change_vartype(dimod.BINARY, inplace=True)

        # embedding
        embedding = {0: ['a', 'b'], 1: ['c'], 2: ['d']}
        graph = nx.cycle_graph(['a', 'b', 'c', 'd'])
        graph.add_edge('a', 'c')

        print(bqm.spin)

        # embed
        embedded = dimod.embed_bqm(bqm, embedding, graph, chain_strength=1)

        print(embedded.spin)
```
Output:
```
BinaryQuadraticModel({0: 0.0, 1: 0.0, 2: 0.0}, {(0, 1): 1.0, (1, 2): 1.0, (0, 2): 1.0}, 0.0, Vartype.SPIN)
BinaryQuadraticModel({'a': 0.5, 'b': -0.5, 'c': 0.0, 'd': 0.0}, {('a', 'c'): 0.5, ('b', 'c'): 0.5, ('c', 'd'): 1.0, ('a', 'd'): 1.0, ('a', 'b'): -1.0}, 1.0, Vartype.SPIN)
```

**Comment by arcondello** [comment]
A solution is to add a parameter to `embed_bqm` that forces the bias smearing to happen in either spin/binary space.

`embedded_bqm = dimod.embed_bqm(bqm, embedding, graph, chain_strength=1, embedding_basis=dimod.SPIN)`
