### ISSUE TITLE
Feature Request: Throw warning when unembedding results in too many chain breaks

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#246]
Proposed syntax:
```
resp = unembed_response(response, embedding, bqm, warning_threshold=.1)
```
In this case a `UserWarning` will be raised if more than 10% of the chains are broken.

**Comment by arcondello** [comment]
@jking-ca

**Comment by JoelPasvolsky** [comment]
relates to Add chain stats to response #197

**Comment by arcondello** [comment]
This warning would include some description of strategies to address the problem, possibly a documentation link.

**Comment by arcondello** [comment]
Alternatives:
* throw a warning only when 100% of the samples have at least one broken chain
* add a new data vector / record field to the resp that says what percentage of chains were broken in each sample.
