### ISSUE TITLE
Template for Feature Request

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#258]
**Application**
What is the need this feature fulfills? If your feature relates to a problem, please provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]. If it relates to a class of real-world problems, please provide an example.

**Proposed Solution**

**Alternatives Considered**
Description of any alternative solutions or features you've considered.

**Additional Context**
Add any other context here.

**Comment by arcondello** [comment]
This should be a pull request
