### ISSUE TITLE
Support metadata in COO (like vartype)

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#262]
**Application**
Currently, (de-)serialization of BQMs is partial and with loss of information - vartype is not stored/loaded.

It would be nice to have a complete (de-)serialization of BQM to COO format, like we already have for JSON and BSON. E.g.:
```
bqm = BinaryQuadraticModel.from_coo(fp)
bqm.to_coo(fp)
```

**Proposed Solution**
Support `vartype` via `p` or `c` in COO.

**Comment by randomir** [comment]
I see the proposed `p` and `c` metadata lines (for program and comment) are qbsolv-specific, and not a part of COO.

As an alternative, I propose we adopt and adapt *magic comments* from [PEP-263](https://www.python.org/dev/peps/pep-0263/).

**Comment by arcondello** [comment]
I would prefer to stop short of requiring the header
```
with open('qubo.q') as fp:
    bqm.to_coo(fp, vartype_header=True)
```
we could then make the vartype a keyword parameters and throw a fit if it's not provided and there is no header?

**Comment by randomir** [comment]
Sure, we don't need to require header. Comments would be optional.

**Comment by randomir** [comment]
Cool, that makes these valid too:
```
# my_precious_vartype=SPINGLASS #
# !!! don't use vartype: BINARY, rather use vartype = SPINNER !!!
# set x-vartype=BINARY
# unset vartype:SPIN
```
:)
