### ISSUE TITLE
Consistent variable order for integer-labelled responses

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#267]
**Application**
When using index labels, it would be nice if the samples in `response.record.sample` where column-ordered by index. This would save needing to do things like `response.record.sample[label_to_idx[0]]`. There is a small performance benefit (skipping the dict look up), and it results in cleaner code. I also think that this might be the less unexpected behaviour, though I do like the consistency of the current approach.

**Proposed Solution/Alternatives Considered**

Three options occur to me:
1) On construction of the response object, we could check that the labels are [0,n) and in that case, sort.
2) Add a kwarg that would toggle the sorting behaviour, perhaps defaulting to True
3) Do nothing but update the existing solvers to return the samples in the appropriate order

@caja-matematica @sploiber

**Comment by arcondello** [comment]
On the balance I am also leaning towards option 3. My only concern with the last option is that we might train people to expect index labels to be sorted, but rely on each sampler author to maintain that behaviour.

**Comment by caja-matematica** [comment]
If I understand you correctly, is it possible to combine option 3 with a toggle from 2. That way if a sampler author creates Response objects that doe not need/can't handle sorted labels then the behavior can be turned off (defaulting to True in this case).

**Comment by dixr** [comment]
From a customer/user perspective, I would definitely welcome this change. The way it is now, it is too easy to end up with seemingly incorrect results from the D-Wave (when you don't know about the inconsistent ordering). Here is a small example that looks reasonable but produces unexpected results:
```python
# qubo:  - q0q2 + q1
# minimum:  [q0 q1 q2] = [1 0 1]
qubo = {(0,2): -1, (1,1): 1}  

sampler = EmbeddingComposite(DWaveSampler())
response = sampler.sample_qubo(qubo, num_reads=100)

for sample, energy, _, _ in response.record:
    print(f'energy={energy} sample={sample}')
```
The output is `energy=-1.0 sample=[0 1 1]`, the expected result would be `energy=-1.0 sample=[1 0 1]`

I think it's confusing if you already label the qubits 0, 1, 2 but BinaryQuadraticModel changes the variable order to 1, 0, 2.

**Comment by arcondello** [comment]
@dixr , thanks for the comment. So I better understand the use case, would
```
for sample, energy in response.data(['sample', 'energy]):
    print(sample, energy)
```
satisfy your needs for now?

**Comment by dixr** [comment]
@arcondello thanks for your reply; yes personally I'm fine with something like
```python
sample = np.asarray(sorted(sample.items()))[:,1] 
```
But I was also thinking about improving the interface so that it is easier to get good results. I know at least two people who thought the results were simply wrong until they looked at the code of BinaryQuadraticModel to find the change in variable order, and there are probably some who just discard the results.
