### ISSUE TITLE
Aggregate unique samples (num_occurrences++) on Response construction

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#268]
**Application**
Right now `Response.from_samples` uses samples verbatim, even if they are identical (same values, same energies) -- although each `Sample` constructed has `num_occurrences` field.

**Proposed Solution**
It would be useful to provide an option to combine identical samples, only summing up the number of occurrences.

**Alternatives Considered**
Aggregate/unique-ify in user code, prior `Response` construction. Implementation on `dimod` side will probably be more efficient and overall convenient for users.

**Comment by arcondello** [comment]
I remember the counter-case, sometimes the order of samples matters, and aggregating them would eliminate that. I think an intermediate solution would be to add a `aggregate_samples()` method that can be called by the user or the sampler author, but in general we would not always keep them aggregated.

**Comment by arcondello** [comment]
Yet another approach would be to aggregate automatically but for the samplers for which order matters, add the order into the `.info` field.

So `[[0, 0], [1, 1], [1, 0], [0, 0]]` would become `[[0, 0], [1, 1], [1, 0]]` with `.info['order'] = [0, 1, 2, 0]`
