### ISSUE TITLE
Allow scaling of subset of bqm biases

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#269]
**Application**
In the case of embedded bqm's, it would be useful to be able to scale the original biases without scaling the chain biases

**Proposed Solution/Alternatives Considered**
Pattern A:
```
bqm.lock_interactions([('a', 'b'), ('b', 'c')])
bqm.scale(.5)
```

Pattern B:
```
bqm.scale(.5, exclude_interactions=[('a', 'b'), ('b', 'c')])
```

@conta877

**Comment by conta877** [comment]
I like B.
