### ISSUE TITLE
extracting whether constraints introduced by make_quadratic are satisfied

### ISSUE THREAD

**Issue by conta877** [dwavesystems/dimod#270]
under dimod.higher_order, we can add a function that takes the bqm object and the response and checks whether the constraints are satisfied for the samples. Can add that as a field to the solution object.

can have a bool field to remove/keep the extra penalty information after/during this step. 

Already have the function ready to do that - let me know if a PR is wanted.

**Comment by conta877** [comment]
Possibly related to #184

**Comment by arcondello** [comment]
Would it be possible to see a code snippet of what you have now? Specifically I am interested in what form you are storing the constraints in.

**Comment by conta877** [comment]
the constraints are stored the way they are implemented in make_quadratic (already in dimod). I'm just taking the constraints and deriving the satisfaction information out of that. adding it as a 4th field to the Response object. ('sample','energy',num_occurrences, 'penalty_satisfied')
