### ISSUE TITLE
Looser `samples_like` in `SampleSet.from_samples`

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#299]
**Application**
```
>>> s1 = [0, 1]
>>> s2 = {0: 1, 1: 0}
>>> dimod.SampleSet.from_samples([s1, s2], vartype='BINARY', energy=[0,0])
....
    raise TypeError("unknown format for samples_like")
TypeError: unknown format for samples_like
```
(`samples_like ~ Iterable[Mapping]` [is enforced](https://github.com/dwavesystems/dimod/blob/79c37c654a64c837cebd84816dabaac710026efc/dimod/sampleset.py#L125))

**Proposed Solution**
If sample is given as a list, assume indices for variable labels.

**Alternatives Considered**
There are many alternatives, this is just a "sugar-y" feature.

**Comment by arcondello** [comment]
I am trying to envision when this would come up outside of testing edge cases?

**Comment by randomir** [comment]
It just seems more consistent. If `from_samples` is accepting (one) sample as a list, and is accepting one sample as a dict, and is accepting a list of lists/dicts; why not the combination?
