### ISSUE TITLE
NameError: name 'itertools' is not defined

### ISSUE THREAD

**Issue by JohnRobson** [dwavesystems/dimod#300]
**Description**
Jupyter "Factoring" Notebook (https://cloud.dwavesys.com/learning/hub/home) works online, but won't work in local machine ("helpers" folder is present).

```
File "Quantum/D-Wave/factoring/01_factoring_full.py", line 104, in <module>
    sample = next(response.samples(n=1))

  File "/usr/lib/python3.7/site-packages/dimod/sampleset.py", line 517, in samples
    for sample in itertools.islice(self.samples(n=None, sorted_by=sorted_by), n):

NameError: name 'itertools' is not defined
```

**Steps To Reproduce**
Source Code:  https://github.com/USP/D-Wave/blob/master/factoring/01_factoring.py#L60-L65

**Environment**
OS: Archlinux Kernel: x86_64 Linux 4.14.72-1-lts
Python version: 3.7.0
dwave-cloud-client           0.4.15            
dwave-drivers                0.4.1             
dwave-neal                   0.4.2             
dwave-networkx               0.6.6             
dwave-ocean-sdk              1.0.1             
dwave-qbsolv                 0.2.9             
dwave-system                 0.5.4             
dwavebinarycsp               0.0.6

**Comment by arcondello** [comment]
Closed by https://github.com/dwavesystems/dimod/pull/296

**Comment by arcondello** [comment]
I will deploy a new version now
