### ISSUE TITLE
Inconsistent signatures: {Response,SampleSet}.from_samples

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#304]
**Description**
Signatures of `Response.from_samples` and `SampleSet.from_samples` functions differ.

**Example**
```
>>> x = dimod.SampleSet.from_samples([0], energy=0, vartype=bqm.vartype)
>>> x = dimod.Response.from_samples([0], energy=0, vartype=bqm.vartype)
TypeError: from_samples() got an unexpected keyword argument 'energy'
```

**Expected Behavior**
Subclass to extend, not break.

**Comment by arcondello** [comment]
This is the intended behaviour to keep Response backwards compatible.
