### ISSUE TITLE
dimod build failing for version 0.7.9 

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#308]
**Description**
>>> dimod.roof_duality.fix_variables(bqm)
Traceback (most recent call last):
  File "C:\Users\me\!git_ADTT\env3_dimod_roof\dimod\dimod\roof_duality\fix_variables.py", line 67, in fix_variables
    from dimod.roof_duality._fix_variables import fix_variables_wrapper
ModuleNotFoundError: No module named 'dimod.roof_duality._fix_variables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\me\!git_ADTT\env3_dimod_roof\dimod\dimod\roof_duality\fix_variables.py", line 69, in fix_variables
    raise ImportError("c++ extension roof_duality is not built")
ImportError: c++ extension roof_duality is not built

**Steps To Reproduce**
WINDOWS:
git clone https://github.com/dwavesystems/dimod.git                                        --> works

pip install -r requirements.txt                                                                               --> couple of errors
Ignoring enum34: markers 'python_version <= "3.3"' don't match your environment
Ignoring futures: markers 'python_version == "2.7"' don't match your environment

python setup.py install
Compiling dimod/roof_duality/_fix_variables.pyx because it changed.
....
creating build\temp.win-amd64-3.6\Release\dimod\roof_duality\src
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Idimod/roof_duality/src/ -IC:\Python36\include -IC:\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" /EHsc /Tpdimod/roof_duality/_fix_variables.cpp /Fobuild\temp.win-amd64-3.6\Release\dimod/roof_duality/_fix_variables.obj
_fix_variables.cpp
dimod/roof_duality/_fix_variables.cpp(2195): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Idimod/roof_duality/src/ -IC:\Python36\include -IC:\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" /EHsc /Tpdimod/roof_duality/src/fix_variables.cpp /Fobuild\temp.win-amd64-3.6\Release\dimod/roof_duality/src/fix_variables.obj
fix_variables.cpp
dimod/roof_duality/src/fix_variables.cpp(29): fatal error C1083: Cannot open include file: 'boost/graph/graph_traits.hpp': No such file or directory
building c++ extensions failed, trying to build without
Finished processing dependencies for dimod==0.7.9

UNIX:
creating build/temp.linux-x86_64-2.7/dimod/roof_duality/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Idimod/roof_duality/src/ -I/usr/include/python2.7 -c dimod/roof_duality/_fix_variables.cpp -o build/temp.linux-x86_64-2.7/dimod/roof_duality/_fix_variables.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Idimod/roof_duality/src/ -I/usr/include/python2.7 -c dimod/roof_duality/src/fix_variables.cpp -o build/temp.linux-x86_64-2.7/dimod/roof_duality/src/fix_variables.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
dimod/roof_duality/src/fix_variables.cpp:29:40: fatal error: boost/graph/graph_traits.hpp: No such file or directory
compilation terminated.
building c++ extensions failed, trying to build without

**Expected Behavior**
Function executes

**Environment**
 - OS: Windows and unix, 
 - Python version: 3.6.5 and 2.7

**Additional Context**
Also the example has "dimod.fix_variables(bqm)" but there's no __all__ so needs "dimod.roof_duality.fix_variables(bqm)"

**Comment by arcondello** [comment]
be patient! the windows wheels are building now

**Comment by JoelPasvolsky** [comment]
![image](https://user-images.githubusercontent.com/34041130/47534325-ca2f5500-d86b-11e8-8dd3-b4089cf1781c.png)


dimod/roof_duality/_fix_variables.cpp(2195): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Idimod/roof_duality/src/ -IC:\Python36\include -IC:\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" /EHsc /Tpdimod/roof_duality/src/fix_variables.cpp /Fobuild\temp.win-amd64-3.6\Release\dimod/roof_duality/src/fix_variables.obj
fix_variables.cpp
dimod/roof_duality/src/fix_variables.cpp(29): fatal error C1083: Cannot open include file: 'boost/graph/graph_traits.hpp': No such file or directory
building c++ extensions failed, trying to build without


>>> dimod.fix_variables(bqm)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dimod' has no attribute 'fix_variables'
>>> dimod.roof_duality.fix_variables(bqm)
Traceback (most recent call last):
  File "C:\Users\jpasvolsky\!git_ADTT\env3_dimod_roof\dimod\dimod\roof_duality\fix_variables.py", line 67, in fix_variables
    from dimod.roof_duality._fix_variables import fix_variables_wrapper
ModuleNotFoundError: No module named 'dimod.roof_duality._fix_variables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jpasvolsky\!git_ADTT\env3_dimod_roof\dimod\dimod\roof_duality\fix_variables.py", line 69, in fix_variables
    raise ImportError("c++ extension roof_duality is not built")
ImportError: c++ extension roof_duality is not built

**Comment by JoelPasvolsky** [comment]
I'm installing from source. Please read the issue.

**Comment by randomir** [comment]
Try after installing Boost.

**Comment by arcondello** [comment]
yes, the install instructions should be updated

**Comment by arcondello** [comment]
to @randomir we can get atomic builds for linux + osx, but there is no (easy) way to sync appveyor and circle that I know of

**Comment by arcondello** [comment]
Also, @JoelPasvolsky in this case I believe it is working as intended. If boost is not installed, then the extensions are not built and you won't have access to the fix_variables module. But the package is otherwise usable

**Comment by JoelPasvolsky** [comment]
Agreed, I'll update the install from source instructions
