### ISSUE TITLE
Windows install broken

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#328]
Wheels for the latest version, 0.7.10, are not available on PyPI, and local `setup.py install` fails (at least for Python 3.4) while trying to compile the roof duality extension.

Error trace available on [a `dwave-hybrid` AppVeyor build](https://ci.appveyor.com/project/dwave-adtt/dwave-hybrid/builds/21110523/job/er0cqyl7o3ark18e).

**Comment by arcondello** [comment]
Yes, I had to revert back to 0.7.9 because of that.
