### ISSUE TITLE
Ability to 'stack' multiple responses

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#349]
**Application**
There are many cases when combining groups of samples (from different samplers say) is useful, however most of the naive approaches are inefficient. We also want to handle edge-cases like differently-ordered labels.

**Proposed Solution**
One of:

Pattern A:
```
combined = sampleset0 + sampleset1
```

Pattern B:
```
dimod.samples_stack(sampleset0, sampleset1)
```

@conta877

**Comment by arcondello** [comment]
Feedback on names for pattern B is appreciated

**Comment by conta877** [comment]
dimod.concat(sampleset0, sampleset1)

**Comment by conta877** [comment]
taking from pandas, append creates a new dataframe. so it is not univeral that append means in place.

**Comment by arcondello** [comment]
Gross. I think pandas is in the wrong here.... But fair point. I like `merge`, `join` and `concatenate`. I think that since order is preserved `concatenate` is least ambiguous.

**Comment by conta877** [comment]
my fav here is concat too.
