### ISSUE TITLE
Include option to compress samples into column of lists in `to_pandas_dataframe`

### ISSUE THREAD

**Issue by jberwald** [dwavesystems/dimod#376]
By default, `to_pandas_dataframe` returns something like 

```python
samples.to_pandas_dataframe()
               a  b  c  energy  num_occurrences
            0 -1  1 -1    -0.5                1
            1 -1 -1  1    -0.5                1
```

It would be nice for downstream applications using DataFrames if all variables were in a list or tuple in a single column. I propose that a flag, say `use_sample_column`, causes the method to collapse all of the variable columns into a single column, such as

```python
samples.to_pandas_dataframe(use_sample_column=True)
                    sample  energy  num_occurrences
            0 [-1,  1, -1]    -0.5                1
            1 [-1 ,-1,  1]    -0.5                1 
```

Something like this should do it:

```python
        samples = list(map(dict, sampleset.samples()))
        df = pd.DataFrame(list(zip(samples,
                                   bqm.energies(samples),
                                   sampleset.record['num_occurrences'])),
                          columns=['sample', 'energy', 'num_occurrences'])
```

**Comment by arcondello** [comment]
One problem that I see is that for labelled samples (e.g. `{'a': -1, 'b': 1}) the proposed format with lists of samples does not work. There are a couple approaches
1) Only allow the sample-column for integer-labelled samplesets and store the samples in numpy vectors. We could also allow the user to specify the variable order like in `BQM.to_numpy_vectors`
2) Store dicts in the sample-column. The problem with this approach is that it gets very memory intensive
3) Mess around with [multiindex](https://pandas.pydata.org/pandas-docs/stable/advanced.html). My experience with multiindices is that they are hard to work with but I am not a pandas expert.

**Comment by arcondello** [comment]
Works for me!

**Comment by jberwald** [comment]
One final comment: It could be hacky, but having two options, `use_sample_column_list` could provide option 1, while `use_sample_column_dict` could be used for option 2. That's only if you think memory would truly be an issue. We can always provide additional workarounds in the future, too.

**Comment by arcondello** [comment]
Yeah, I think we should track usage and if it becomes a problem we can iterate.
