### ISSUE TITLE
Formatter object for printing

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#378]
**Application**
It might be useful to have a more powerful/general formatting object that allows users to customise their printing in-place.

This would generalize the feature added in #370 

**Proposed Solution**
Perhaps something like
```
>>> fmt = SampleSetFormatter()
>>> fmt.pprint(sampleset, linewidth=60)
```

**Additional Context**
* [pprint](https://docs.python.org/3.7/library/pprint.html) library. 
* https://stackoverflow.com/questions/40828173/how-can-i-make-my-class-pretty-printable-in-python

@randomir

**Comment by randomir** [comment]
1) Let's add the stand-alone formatter class, but

2) Plug it into `pprint`'s dispatch for `SampleSet.__repr__`. It's so much better to have the standard pretty printer (and formatter, `pformat`!) working by default/out-of-the-box.

**Comment by arcondello** [comment]
So I have looked into this more and I think this might not be what what we're looking for, specifically because "The pprint module provides a capability to “pretty-print” arbitrary Python data structures in a form _which can be used as input to the interpreter_." ([link](https://docs.python.org/3/library/pprint.html), emphasis mine). So I think it makes sense to make the repr pretty-printable but that is different than the feature introduced in #370 which does not purport to make an string that is interpretable.

**Comment by arcondello** [comment]
Here is the implementation for the record
```
import pprint

import numpy as np

from dimod.sampleset import SampleSet

__all__ = []


if isinstance(getattr(pprint.PrettyPrinter, '_dispatch'), dict):
    # assume the dispatch table method still works
    def pprint_SampleSet(printer, obj, stream, indent, allowance, context, level):

        name = type(obj).__name__
        stream.write(name + '(')

        # first up is the record
        recname = type(obj.record).__name__
        stream.write(recname + '(')

        options = dict(prefix=' '*(indent + len(name) + len(recname) + 2),
                       max_line_width=printer._width,
                       separator=', ')

        stream.write(np.array2string(obj.record, **options))

        stream.write(',\n'+' '*(indent + len(name) + len(recname) + 2))

        stream.write('dtype=[')

        printer._format_items(obj.record.dtype.fields.values(),
                              stream, indent + len(name) + len(recname) + 8,
                              allowance+1, context, level)

        stream.write(']),\n'+' '*(indent + len(name) + 1))

        # now variables, info, vartype
        items = [list(obj.variables),
                 obj.info,
                 obj.vartype.name]

        printer._format_items(items, stream, indent + len(name), allowance+1, context, level)

        stream.write(')')

    pprint.PrettyPrinter._dispatch[SampleSet.__repr__] = pprint_SampleSet
```
Not sure if this is worth doing just to get nice indentation of the sampleset object. It works pretty well but I don't find it significantly more readable that the normal version. Example output:
```
SampleSet(recarray([([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1, 1),
                    ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1, 1),
                    ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1, 1),
                    ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1, 1),
                    ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1, 1),
                    ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1, 1),
                    ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1, 1),
                    ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1, 1),
                    ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1, 1),
                    ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1, 1)],
                   dtype=[(dtype(('i1', (10,))), 0),
                          (dtype('int64'), 10),
                          (dtype('int64'), 18)]),
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
          {},
          'SPIN')
```
It also is not quite right (does not have the field names).

**Comment by randomir** [comment]
I agree that such output is not too valuable.

But the following sentence(s) (after your quote) give as more options: 
> If the formatted structures include objects which are not fundamental Python types, the representation may not be loadable. This may be the case if objects such as files, sockets or classes are included, as well as many other objects which are not representable as Python literals.

Alternatively, we could print a more readable output, not a direct representation of numpy recarrays, that is still a valid Python expression.

Anyway, we don't have to spend too much time on this. Having nice readable text description of the sampleset (that we already do) is highly valuable. Having it as a valid Python expression is just a plus.
