### ISSUE TITLE
Pairwise roof duality

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#380]
We could adapt the current `fix_variables` function to also determine pair-wise whether variables are equal or not equal in the ground states.

**Additional Context**
roof duality is polynomial time, so the pairwise algorithm would be as well.

**Comment by conta877** [comment]
This is some dangerous territory. there is no guarantee that the pair-wise behavior will be that of the ground state if the spin is fixed in wrong direction.

**Comment by arcondello** [comment]
Would the case where the spins are equal or not equal for both possible fixed values work?

**Comment by conta877** [comment]
no it won't

**Comment by arcondello** [comment]
Closing now that roof duality has been moved to [dwave-preprocessing](https://github.com/dwavesystems/dwave-preprocessing)
