### ISSUE TITLE
Support higher order polynomials

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#391]
Right now in dimod there is 'dimod/higherorder.py` which supports higher-order Ising problems. But as this is proving to be a more common use case, we should consider creating a proper `HUBO` (or similar)
class.

We could also define a Sampler ABC similar to `Structured`, to signal samplers/composites that support HUBOs. These would then implement a `sample_hubo` method.

**Comment by conta877** [comment]
this also effects #330 and #372
