### ISSUE TITLE
Remove blank line in sampleset printing

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#441]
**Application**
It looks like sphinx-builder has a bug that \<BLANKLINE\>, which should be used by the doctest builder, is instead rendered by other builders. So inserting the \<BLANKLINE\> directive doesn't help pass doctests and appears in the HTML output. Not using the directive messes up the HTML:

![image](https://user-images.githubusercontent.com/34041130/54557538-a256a000-4978-11e9-9cf3-2c767eeb438a.png)
  

**Proposed Solution**
If there isn't a blank line the problem goes away

**Alternatives Considered**
Putting in \<BLANKLINE\>, skipping doctests, and hoping a new version of sphinx-build fixes the bug

**Additional Context**
https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html: "Note that like with standard doctests, you have to use \<BLANKLINE\> to signal a blank line in the expected output. The \<BLANKLINE\> is removed when building presentation output (HTML, LaTeX etc.)."

**Comment by JoelPasvolsky** [comment]
BTW, in the problem description above the <--BLANKLINE--> directive is rendered invisible so it's hard to read the description :-)

**Comment by arcondello** [comment]
Good news! This was removed in #427 , upgrading to dimod 0.8.7 should resolve the issue

**Comment by JoelPasvolsky** [comment]
It does, thanks!
