### ISSUE TITLE
dimod.generators.combinations should accept vartype=SPIN

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#452]
**Description**
dimod.generators.combinations() claims to work for either vartype ("Accepted input values: Vartype.SPIN, 'SPIN', {-1, 1} Vartype.BINARY, 'BINARY', {0, 1}") and that "energy for the binary quadratic model is given by    :math:`(\sum_{i} x_i - k)^2`" but that is true only for vartype=BINARY, because that's hardcoded now "bqm.add_variables_from(((v, lbias) for v in variables), vartype=BINARY)" etc.

**Steps To Reproduce**
```
>>> my_bqm2 = dimod.generators.combinations(['a', 'b', 'c', 'd'], 2, strength=1, vartype='SPIN')
>>>  my_bqm2.energy({'a': 0, 'b': 0, 'c': 1, 'd': 1})
1.5
```

**Expected Behavior**
Unless we specify that this is for binary variables, the code should convert from SPIN

**Environment**
Win and python 3.x

**Additional Context**
I think it's preferable to enable both vartype values rather than limit and document the limitation

**Comment by JoelPasvolsky** [comment]
My bad, sorry

**Comment by arcondello** [comment]
For posterity, the problem was the sample in
```
>>> my_bqm2 = dimod.generators.combinations(['a', 'b', 'c', 'd'], 2, strength=1, vartype='SPIN')
>>>  my_bqm2.energy({'a': 0, 'b': 0, 'c': 1, 'd': 1})
1.5
```
was binary-valued. The correct form would be
```
>>> my_bqm2 = dimod.generators.combinations(['a', 'b', 'c', 'd'], 2, strength=1, vartype='SPIN')
>>>  my_bqm2.energy({'a': -1, 'b': -1, 'c': 1, 'd': 1})
0.0
```
This does touch on #244 in the sense that `bqm.energy` does not complain when the wrong vartype sample is given.
