### ISSUE TITLE
Pickling SampleSets fails for sample sets with unresolved futures

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#474]
When pickling a `SampleSet` with an unresolved future, the sample set should wait until the future is resolved

**Comment by jberwald** [comment]
If some other process is doing the pickling can SampleSet block until the future is resolved? Thinking of issues with PySpark and having to explicitly return `sampleset.record` to enable pickling.

**Comment by arcondello** [comment]
Yes, this would cover that case
