### ISSUE TITLE
A sampler for composites that will not sample but give access to modified problem

### ISSUE THREAD

**Issue by conta877** [dwavesystems/dimod#481]
It would be cool to have a "sampler" that does not do sampling but gives access to the problem that is generated by the composite. 

I'm thinking something like
```
sampler = Composite(SaidSampler())
response = sampler.sample_ising(h,J,**kwargs)
response.bqm
response.h
response.j
```

and such.

**Comment by arcondello** [comment]
How about something like
```
>>> sampler = Composite(SaidSampler())
>>> sampleset = sampler.sample(bqm, **kwargs)  # or sample_ising or whatever
>>> sampleset.record.samples.shape[0]
0
>>> sampleset.record.samples.shape[1] == len(bqm)
True
>>> sampleset['info']['bqm'] == bqm
True
```

**Comment by conta877** [comment]
yeah that looks good

**Comment by arcondello** [comment]
Maybe this should be a composite? And we should have a "null" sampler that always just returns an empty sampleset? Those two features seem useful but conceptually separate.

**Comment by conta877** [comment]
I don't know how that would work

**Comment by arcondello** [comment]
Object names not final obviously:

*TrackingComposite*
Would add to `info` the inputs and outputs received by the composite
```
>>> sampler = TrackingComposite(ExactSolver())
>>> sampleset = sampler.sample(bqm, a=6)  # or sample_ising or whatever
>>> sampleset['info']
{'inputs': {'bqm': BinaryQuadraticModel(...), 'a': 6},
 'outputs': SampleSet(...)}
```
*NullSampler*
Would always just return an empy sample set
```
>>> sampleset = NullSampler.sample(bqm)
>>> sampleset.record.samples.shape[0]
0
>>> sampleset.record.samples.shape[1] == len(bqm)
True
```

**Comment by conta877** [comment]
hmm.. ok.. any reason why you want to divide into two?

**Comment by randomir** [comment]
I like the tracking composite, but how would nesting work?
```
>>> TrackingComposite(EmbeddingComposite(TrackingComposite(ExactSolver()))).sample()['info']
?
```

**Comment by conta877** [comment]
yeah... that's why i was suggesting a sampler.

another option, which i believe ppl are gonna hate, is every composite now adds its name to bqms info field.

**Comment by arcondello** [comment]
@conta877 Just because I like things to do just one thing. And I can imagine wanting just one of the two uses without the other.

@randomir That's a good point, something like
```
TrackingComposite(sampler, tag='hello')
```
seems simple/obvious. Otherwise the outermost.

**Comment by conta877** [comment]
I like tag

**Comment by randomir** [comment]
Hm. Sure, tags could work. They are a bit too explicit/verbose for my taste. I was imagining some kind of info dicts nesting, but that’s probably too magical..

There’s also the option from Hybrid / hybrid.TrackMin - keep debugging info in the object (composite here), not the result.

**Comment by arcondello** [comment]
https://github.com/dwavesystems/dwave-hybrid/blob/0f74d7dd2a533edc34cc6808107760ca61cbc0fa/hybrid/flow.py#L603
for future reference.

**Comment by arcondello** [comment]
I think keeping them in the object makes sense. It's slightly less convenient for deeply-nested composed samplers but it keeps things clean.
