### ISSUE TITLE
BinaryQuadraticModel.vartype unexpected behaviour

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#489]
The correct way to change `BQM.vartype` is with the change_vartype method. Setting it directly does not change the biases, which may be unexpected.

*Proposed Solution*
`BQM.vartype` should be made a getter.

Either:
* The setter should not be implemented, to make `vartype` 'read-only'
* The setter should wrap `change_vartype`

**Comment by randomir** [comment]
Setter solution seems too magical.

Implementing `.vartype` as a getter, thus making it a read-only property, seems like the pythonic way to go.
