### ISSUE TITLE
sampleset.to_serializable to check variable indices

### ISSUE THREAD

**Issue by conta877** [dwavesystems/dimod#496]
when using to_serializable, seems like it doesn't check the type of variable indices.
if np.int64 is sent it as variable indices, sampleset.to_serializable() remains not bson compatible. 

would be nice if we can check that and convert during the process

**Comment by arcondello** [comment]
Can you provide a failing example?

**Comment by conta877** [comment]
```
from dwave.system import DWaveSampler

sampler = DWaveSampler()
qubit_indices = np.arange(0,8)
h = {q:1 for q in qubit_indices}
r = sampler.sample_ising(h,{},num_reads = 5)
serialized = r.to_serializable()
try:
    bson.BSON.encode(serialized)
except Exception as e:
    print(e)
```
Returns
`cannot encode object: 0, of type: <class 'numpy.int64'>
`

**Comment by arcondello** [comment]
Got it. I thought you were referring to the [irow, icol](https://github.com/dwavesystems/dimod/blob/4920d4e490a40ae69fafb4709ff8cc91059feb79/dimod/binary_quadratic_model.py#L1754).

I do agree that `BQM.to_serializable` should make sure that the variable labels are in a serializable form.  Which does make this a bug!
