### ISSUE TITLE
Deploy fails on manylinux (v0.8.15 affected)

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#514]
Due to `pandas==0.23.4` **not** being available for Python 3.4, [wheel build/deploy fails on manylinux](https://circleci.com/gh/dwavesystems/dimod/7597).

The last version of Pandas built for Python 3.4 is v0.19.2 from 2016.

We should drop dimod wheel building for Python 3.4. Maybe even drop support for 3.4 altogether.

**Comment by arcondello** [comment]
Looks like the failure is actually for `cp27-27mu`, it correctly installs for `cp27-27m`, see [docs](https://github.com/pypa/manylinux#docker-images) for distinction.

I have changed the requirements to only install pandas in 3.5+, though agree we should drop 3.4 support (https://github.com/dwavesystems/dwave-ocean-sdk/issues/28). Also I accidentally pushed the change to master so no PR to close this one, oops...

**Comment by arcondello** [comment]
Wheels are deployed

**Comment by randomir** [comment]
@arcondello, are you saying the failure is *also* for `cp27mu`? Because that pandas version fails on python 3.4 for sure.

**Comment by arcondello** [comment]
Yes but we skipped the pandas install for python 3.4 already https://github.com/dwavesystems/dimod/blob/5dfc00b087a4270535ae6c1bcb25f9ebeea36dee/requirements.txt#L8
