### ISSUE TITLE
Binary wheels for Windows, Python x64 3.6+ compiled to use FH4 (`__CxxFrameHandler4`) available only since MSVC 2019 Preview 2

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#577]
Affected OS: Windows
Affected Pythons: 64-bit 3.6+
Affected functionality: `dimod.roof_duality.fix_variables`
Affected CI: CircleCI, not AppVeyor
Proof: https://ci.appveyor.com/project/dwave-adtt/dwave-hybrid/builds/30045253

Reason: new [C++ exception handling (called FH4)](https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/), introduced in ~2019-03 (Visual Studio 2019 Preview 2 [release notes](https://habr.com/en/company/microsoft/blog/437670/)), but enabled by default during compile/link only ~2019-07.

Manifestation: binary module/DLL `dimod.roof_duality._fix_variables.cp3x-win_amd64.pyd` imports `__CxxFrameHandler4` from `vcruntime140_1.dll`, but that DLL is distributed in vc_redist.x64 v14.23+.

Possible fixes:
- require from users to install the latest vcredist, e.g. [this one](https://aka.ms/vs/16/release/vc_redist.x64.exe) from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
- statically link `vcruntime140_1.dll` with `_fix_variables` module
- use older exception handling routine, FH3 (see how [here](https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/#comment-510))

**Comment by arcondello** [comment]
Closed by #590
