### ISSUE TITLE
Fix ScaleComposite to not use info field

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#628]
Right now the `ScaleComposite` relies on `BQM.info` which has been deprecated as of [0.9.0](https://github.com/dwavesystems/dimod/releases/tag/0.9.0).

See https://github.com/dwavesystems/dimod/pull/627/files#diff-650a9a798c6df570212e820d8acc920bR122 in #627

**Comment by conta877** [comment]
so you don't want the scale information to be returned?

**Comment by arcondello** [comment]
It can be in the sample set

**Comment by arcondello** [comment]
I think https://github.com/dwavesystems/dimod/blob/fa7ee3d6ab63e0fbe799090d86952ef1255944d5/dimod/reference/composites/scalecomposite.py#L125
could return the scale value instead of putting it in the info field. We can then keep https://github.com/dwavesystems/dimod/blob/fa7ee3d6ab63e0fbe799090d86952ef1255944d5/dimod/reference/composites/scalecomposite.py#L130

**Comment by conta877** [comment]
yeah thats how I changed it - and puts in to the sampleSet object info field at the end.
