### ISSUE TITLE
BinaryQuadraticModel.add_variable documentation is out of date

### ISSUE THREAD

**Issue by spakin** [dwavesystems/dimod#635]
**Description**

The documentation at https://docs.ocean.dwavesys.com/projects/dimod/en/latest/reference/bqm/generated/dimod.BinaryQuadraticModel.add_variable.html claims that `dimod.BinaryQuadraticModel.add_variable` accepts a `vartype` argument, but the [latest definition of `add_variable`](https://github.com/dwavesystems/dimod/blob/b9ac773208f8e1ebc81b01ee5d637ed4800a7c68/dimod/core/bqm.py#L979) has dropped this parameter.

**Steps To Reproduce**

```Python
import dimod
bqm = dimod.BinaryQuadraticModel({1: 0.0, 2: 0.0}, {(0, 1): 1.0, (0, 2): 1.0, (1, 2): 1.0}, 0.0, dimod.SPIN)
bqm.add_variable(0, 0.0, dimod.SPIN)
```

⇨ `TypeError: add_variable() takes from 1 to 3 positional arguments but 4 were given`

**Expected Behavior**

No output

**Environment**

 - OS: Ubuntu 19.10
 - Python version: 3.8.1

`pip install dwave-ocean-sdk` from a fresh Conda environment.

**Comment by arcondello** [comment]
This is an artefact of the way that our documentation is hosted - it only gets updated once the sdk has the new version of the package. I'll push an update and close this issue once it's fixed.

**Comment by arcondello** [comment]
Hi Scott, here is the new, fixed, documentation https://docs.ocean.dwavesys.com/en/latest/docs_dimod/reference/generated/dimod.AdjDictBQM.add_variable.html#dimod.AdjDictBQM.add_variable

**Comment by spakin** [comment]
Thanks!
