### ISSUE TITLE
ising_to_qubo fails if J contains nodes not in h

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#650]
**Description**
`dimod.ising_to_qubo({}, {(1,2): 1})` gives a key error. The function seems to work only if all nodes specified in `J` are also specified in `h`:
```
>>> dimod.ising_to_qubo({1: 1, 2: 1}, {(1,2): 1})
({(1, 1): 0.0, (2, 2): 0.0, (1, 2): 4.0}, -1.0)
```
But `h={}`, `h={1: 1}`, or `h={2: 1}` give a key error; e.g.:
```
    206         q[(u, v)] = 4. * bias
    207         q[(u, u)] -= 2. * bias
--> 208         q[(v, v)] -= 2. * bias
    209
    210     # finally calculate the offset

KeyError: (2, 2)
```

**Steps To Reproduce**
`dimod.ising_to_qubo({}, {(1,2): 1})`

**Expected Behavior**
J nodes alone should be accepted with h nodes implicitly set to zero.

**Environment**
 - OS: Windows and IDE
 - Python version: 3.x

**Additional Context**
I think this used to work

**Comment by arcondello** [comment]
I think this is consistent with the behavior from the [legacy sapi clients](https://github.com/dwavesystems/legacy-sapi-clients). Based on a quick look at the git history, I don't think this ever worked. We can definitely update the behavior.
