### ISSUE TITLE
Installing dimond fails due to boost errors

### ISSUE THREAD

**Issue by theerfan** [dwavesystems/dimod#732]
**Description**
I tried to install via pip but I got the following error even though boost is installed and BOOST_ROOT environment variable is set.
`dimod/roof_duality/src/fix_variables.cpp(30): fatal error C1083: Cannot open include file: 'boost/graph/graph_traits.hpp': No such file or directory`
Then I tried to install via source, but I got the same error.
This time I copied boost\boost_1_62_0\boost to dimod\dimod\roof_duality\src and it passed that stage, and after that it encounters a huge amount of the same syntax error, a sample of which you can see below:
![image](https://user-images.githubusercontent.com/11455681/96185737-36b72900-0f47-11eb-93c7-0c3486e12e03.png)

How can I get past all these errors? 

**Environment**
 - OS: Windows 10 x64
 - Python version: 3.9.0

**Comment by arcondello** [comment]
What command are you using to install?

Also, there is not yet a numpy wheel for python 3.9, are you installing that from source as well?

**Comment by theerfan** [comment]
I'm using `python setup.py install`.
And numpy was installed after running `pip install -r requirements.txt` in the source folder.

**Comment by arcondello** [comment]
If possible, I would recommend downgrading to python 3.8 until it is supported by more of the open source ecosystem and we can build wheels for it.

If you need to use 3.9, I'll need the full traceback to better diagnose.

**Comment by theerfan** [comment]
I would really appreciate it if you did the diagnosis.
I have attached the entire log.
[log.txt](https://github.com/dwavesystems/dimod/files/5387896/log.txt)

**Comment by arcondello** [comment]
It looks to me like your compiler is too modern :smile: 

If you change `/std:c++latest` in
https://github.com/dwavesystems/dimod/blob/9af460dc0f9028a1292cf786063c278cae3c0c80/setup.py#L72
to `/std:c11` does it work then?

**Comment by theerfan** [comment]
It worked with `std:c11`, thanks! 
(Although I suggest you add the same trick to the project's README or change the setup.py altogether. xD)

**Comment by arcondello** [comment]
Yeah, will reopen this until I can make a PR to fix the setup
