### ISSUE TITLE
add_offset for DQM

### ISSUE THREAD

**Issue by hay-k** [dwavesystems/dimod#744]
**Application**
In some applications the energy value of a sample has an important meaning to it. For instance I am working on a graph partitioning problem, and due to the structure of the cost function for this problem, the energy value of a sample (offsets included) is exactly the number of cut edges between the partitions. You get the energy of a sample and you know the number of cut edges right away and you don't need to traverse the graph one more time to count the cut edges. When formulating a problem in terms of a DQM, one usually throws away any constant offset which appear on the way, but in problems like this it is sometimes convenient to keep the constants. BQM has a function called `add_offset` which allows to do this.

**Proposed Solution**
Implement `add_offset` function for DQM as well. 

**Alternatives Considered**
I am currently calculating the offset in a separate variable, so that I can add it to the energy of the result after sampling.

**Comment by arcondello** [comment]
I agree with adding an offset to DQM. However, I would just add a property so the syntax would be `dqm.offset += 1`rather than `dqm.add_offset(1)`
