### ISSUE TITLE
Typo in BQM repr

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#747]
```
>>> dimod.BQM.from_ising({}, {'ab': 1})
BinaryQuadraticModel({a: 0.0, b: 0.0}, {('a', 'b'): 1}, 0, 'SPIN')
                      ▲       ▲
                      ┗━━━━━━━┻━━━━━━━  should be quoted
```
Also, at least for the `AdjDictBQM`, linear biases are stored (and printed) as floats, and quadratic/offset preserve the input type.

**Comment by arcondello** [comment]
Good catch, comes from https://github.com/dwavesystems/dimod/blob/4941d2301aca0dc2c61b586605d0d3c69e2a7320/dimod/core/bqm.py#L59

Will fix.

**Comment by mcfarljm** [comment]
Possible fix:
```python
            conv = str if isinstance(key, tuple) else repr
            stream.write('{}: {!s}'.format(conv(key), value))
```
Gives:
```
In [2]: dimod.BQM.from_ising({}, {'ab':1})
Out[2]: BinaryQuadraticModel({'a': 0.0, 'b': 0.0}, {('a', 'b'): 1}, 0, 'SPIN')
```

Also there is a line in the doc for `flip_variable` that has this issue as well:
https://github.com/dwavesystems/dimod/blob/dc98404439114f075aa7c0ff979ad30079eab2e4/dimod/core/bqm.py#L548-L552

**Comment by arcondello** [comment]
I think just `stream.write('{!r}: {!r}'.format(key, value))` is the most explicit fix

**Comment by randomir** [comment]
Yes, `repr`/`{!r}` is the correct solution, IMO, since the whole output is `repr(bqm)` in spirit.

Another manifestation of this bug:
```
>>> dimod.BQM.from_ising({0: 1, '0': 1}, {})                                                                                                                                                                  
BinaryQuadraticModel({0: 1, 0: 1}, {}, 0, 'SPIN')
                      ▲     ▲
                      ┗━━━━━┻━━━━━━━  indiscernible
```
