### ISSUE TITLE
AdjArrayBQM.to_numpy_vectors does not raise ValueError if len(variable_order) != num_variables

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#751]
**Description**
ValueError is not checked in AdjArrayBQM of `to_numpy_vectors`

**Steps To Reproduce**
```
>>> bqm = dimod.AdjArrayBQM.from_ising({'a': 1.1, 'b': 1.2, 'c': 1.3}, {('ab'): 2.1, ('bc'): 2.2, ('ac'): 2.3})
>>> bqm.to_numpy_vectors(variable_order=['a'])
(array([1.1, 2.3, 2.2]),
 (array([4294967295, 4294967295, 4294967295], dtype=uint32),
  array([         0,          0, 4294967295], dtype=uint32),
  array([2.1, 2.3, 2.2])),
 0.0)
```

**Expected Behavior**
bqm.py implements a ValueError:
```
if len(variable_order) != num_variables:
            raise ValueError("variable_order does not match the number of "
                             "variables")
```

**Environment**
 - OS: WIN
 - Python version: 3.6

**Additional Context**
Add any other background information about the problem.

**Comment by arcondello** [comment]
Probably applies to all, should be fixed as part of https://github.com/dwavesystems/dimod/issues/653

**Comment by arcondello** [comment]
`AdjArrayBQM` has been removed as of #786
