### ISSUE TITLE
Accessing DQM variables with np.int64, etc. array integer elements throws ValueError

### ISSUE THREAD

**Issue by hbarovertwo** [dwavesystems/dimod#778]
**Description**
When I use a numpy array with `np.int64`,  `np.int32`, or `np.uint16`  integer elements to label DQM variables, accessing the variables through DQM method `num_cases(...)` fails with integer elements from the numpy array used to apply labels.

**Steps To Reproduce**
```
import numpy as np
from dimod import DQM

dqm = DQM()

variables = np.array([0,1,2], dtype=np.int64)

for variable in variables:
    dqm.add_variable(num_cases=5, label=variable)

dqm.num_cases(variables[0])
>>>ValueError: unknown variable 0
```

However this works fine to access:
`dqm.num_cases(0)`

**Expected Behavior**
To be able to access the variable by the (numpy) integer label used to create it.

**Environment**
 - OS: Windows 10 Pro 64-bit, Ubuntu 20.04 LTS
 - Python version: 3.8.5

**Additional Context**
Observed in dimod versions `0.9.10`, `0.9.13`

**Comment by arcondello** [comment]
Happens because in the sparse variable representation we check equality. `int(1) == np.int(1)` but they hash differently. Will fix.

**Comment by hbarovertwo** [comment]
> Happens because in the sparse variable representation we check equality. `int(1) == np.int(1)` but they hash differently. Will fix.

Great! Once ready either you or I could add a regression test if it's appropriate?
