### ISSUE TITLE
Sporadic CI failures in manylinux

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#791]
Recently PRs have had sporadically failing CI jobs (see #787, #788). The jobs are failing on the `yum install -y boost-devel` build step. I have installed the `manylinux1` docker image locally and verified that I am also getting sporadic failures. This seems to be due to Centos5's continued EOL. Specifically, I suspect that there are fewer and fewer mirrors for yum package repositories available, so the wait time is getting longer.

See also: https://github.com/pypa/manylinux/issues/102, https://github.com/pypa/manylinux/issues/103

Typical error:
```
yum install -y boost-devel
extras                                                                                           | 2.1 kB     00:00
extras/primary_db                                                                                | 173 kB     00:00
http://vault.centos.org/5.11/centosplus/x86_64/repodata/repomd.xml: [Errno 4] IOError: <urlopen error (99, 'Cannot assign requested address')>
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: libselinux. Please verify its path and try again
```
though which package it fails on varies

Some suggested fixes:
1) Play with `yum`'s flags/features. Notably there are `-R` (maximum command wait time) and `-t` (tolerant).
    - I tried `-R10 -t` and that did not reliably fix the problem.
    - We could possibly find a specific mirror that we like and point directly to that.
    - I also tried getting boost with `wget`, but of course that is not installed in the image and getting it normally means using `yum`. This way lies madness.
    - I also also tried most of the basic fixes outlined in https://unix.stackexchange.com/questions/109585/yum-update-fails-error-cannot-retrieve-repository-metadata-repomd-xml-for-re and similar.
2) Use `manylinux2010` rather than `manylinux1`. This [requires pip>19.0](https://github.com/pypa/manylinux/blob/master/README.rst) which was released [Jan 22, 2019](https://pypi.org/project/pip/19.0/).
3) Hard-deprecate roof-duality. We were planning to do that anyway (see https://github.com/dwavesystems/dimod/pull/748), and we're currently working on a 0.10.x release, but this would be a pretty sudden change.
4) Install boost in a non-Centos build step, then save it in the cache and use it in the subsequent build step. This solves the issue, but complicates the CI even more than it already is.
5) Open up an issue on manylinux and let them handle it. I suspect that they'll say we should go with (2).
6) Combo of (2) and (3), where we support roof duality only in `manylinux2010`.

I am currently inclined towards (2), but wanted to open it up for discussion.

**Comment by arcondello** [comment]
And of course, option (7), it magically fixes itself. There have been a few PRs today that have gone through fine. Of course it seemed to fix itself yesterday afternoon too. We'll see what tomorrow brings...

**Comment by randomir** [comment]
Obviously, at some point, we'll want to switch to `manylinux2010` (hopefully _before_ CentOS 6 EOL :rofl:). I see numpy releases all three `manylinux{1,2010,2014}`, pandas only manylinux1 and tensorflow only manylinux2010.

But I don't think we should just immediately drop `manylinux1`, as we have a wide linux user base. Officially, Ubuntu 16.04 LTS has [end of standard support April 2021](https://wiki.ubuntu.com/Releases) (EOL April 2024) and ships with pip 8.1.1.

So, I'm inclined with (1'), and then (2) after April 2021.

Fixing yum install should be easy. I'd just use the [official archive](https://vault.centos.org/5.11/) instead of unreliable mirrors.

**Comment by arcondello** [comment]
The `yum` install already tried the official archive, then mirrors. That seems to be the thing that's failing. Though maybe something temporary was happening with it, so that would give us (7).

I am not sure that hosting our own manylinux image is worth the work, they update it fairly regularly it looks like so we'd have to stay up to date to always have the latest and greatest.

I can look into the `curl` download.

**Comment by randomir** [comment]
Yes, I missed your links to those issues 102/103 at first.

Might be an issue with CircleCi network, again. :shrug:

**Comment by arcondello** [comment]
I had the same issues with a local install of the `manylinux1` image, so for once we cannot blame them! :laughing:

**Comment by randomir** [comment]
Haha, ok not this time then :smile:

**Comment by arcondello** [comment]
This issue has not reappeared, so closing as a stale issue
