### ISSUE TITLE
DQM variable case labeling

### ISSUE THREAD

**Issue by seatim** [dwavesystems/dimod#840]
**Application**

It is common for optimization practitioners to use labels to refer to cases of discrete variables in the same way as one does binary variables (e.g. "x11", "x12", "x13" for a discrete variable "x1" with three cases).

Another use case is where the cases of different variables have the same meaning, but the variables have a different number (or set) of cases.  For example, say variable "c1" has cases "red", "green", and "blue", and variable "c2" has cases "blue", and "yellow", and "brown".

DQM currently only supports the use of integers 0 .. N-1 to identify cases of variables with N cases.

**Proposed Solution**

Summary

Introduce an ability to refer to cases of discrete variables using labels, as an alternative to integers.  Case labels may be model-unique (unique within a model), or shared (unique within each variable, but shared among variables).

_Model-unique case labels_ are useful as they are a type of notation that is familiar to optimization practitioners.  These are semantically equivalent to sets of binary variables subject to one-hot constraints.

_Shared case labels_ are useful in that they allow cases to be labeled consistently by variables that have different numbers or sets of cases.

High-level Design

1. Introduce a subclass of DQM called `CaseLabelDQM` to offer both kinds of variable case labels.
2. Introduce `DQMCaseLabelComposite` class to map samples, translating both types of case labels.

CaseLabelDQM Methods

1. `add_variable(cases, label=None)`
    1. accept `Iterable` as value for `cases` parameter in addition to int.
    2. when `cases` is an `Iterable`:
        1. its values are case labels.  Labels can be any hashable object.
        2. when `label` is not `None`, shared case labels are defined. `ValueError` is raised if any label is repeated in cases.
        3. when `label` is `None`, model-unique case labels are defined. `ValueError` is raised if any label is not unique within the model among model-unique case labels and discrete variable labels.

    3. when `cases` is an int:
        1. no case labels are defined.
                OR: shared case labels `{ 1, ..., cases }` are created and `label` must not be `None`
                    NOTE: These are equivalent and the latter could be an implementation detail EXCEPT for the "label must not be None" part.
        2. behaves same as base class EXCEPT that if `label` is not `None`, it must be unique among model-unique case labels and discrete variable labels, else `ValueError` will be raised.

2. `get_linear(v)`
    `set_linear(v, biases)`
    - `v` may be a model-unique case label.

3. `get_linear_case(v, case)`
    `set_linear_case(v, case, bias)`
    - `case` may be a shared case label.

4. `get_quadratic(u, v)`
    `set_quadratic(u, v, biases)`
    - `u` and/or `v` may be model-unique case labels.

5. `get_quadratic_case(u, u_case, v, v_case)`
    `set_quadratic_case(u, u_case, v, v_case, bias)`
    - `u_case` and/or `v_case` may be shared case labels.

DQMCaseLabelComposite Behavior

1. Each model-unique case label appears as a distinct variable (i.e. in its own column) in a `SampleSet`.
2. Shared case labels appear as the values of their variables (where previously the integer case values would appear).

**Alternatives Considered**

1. Considered changing DQM directly instead of a subclass.
2. Considered utility function or method to transform samples instead of a Composite.

**Additional Context**

A prototype of `CaseLabelDQM`, implementing shared case labels, is used in the [crop rotation example](https://github.com/dwave-examples/crop-rotation/).

**Comment by seatim** [comment]
- REQUIREMENT:

    - users submitting a `CLDQM` to `LeapHybridDQMSampler` must see either an
        error or a properly case-labeled `Sampleset` (what `CLDQMComposite`
        would return)

    - if `CLDQM.to_file()` does not raise `NotImplementedError`, we must
        implement faithful serialization, i.e. a new binary format.
                                                                 
- DESIGN:

    - define `CLDQM.to_file()` and have it raise `NotImplementedError`, because
        otherwise when someone submits a `CLDQM` to
        `LeapHybridDQMSampler` without using the composite, they will get an unlabeled
        `SampleSet` back and be confused.
        
        - this is because `LeapHybridDQMSampler` calls `dqm.to_file()`.
            
- IMPLEMENTATION DETAIL:

    - `CLDQM` will need to implement a method to return a `DQM` that is a shallow
        copy (ideally a "view") of itself, as the `CLDQMComposite` must pass an
        ~~DQM~~ object that has a `to_file()` method that returns a serialization
        of a `DQM`, to `LeapHybridDQMSampler`.

**Comment by arcondello** [comment]
As an alternative, we could update `LeapHybridDQMSampler` to handle `CLDQM` directly, and not have to implement a composite at all.

Pro:
* simpler from a user perspective

Cons:
* tightly couples `CLDQM` and the `LeapHybridDQMSampler`

**Comment by seatim** [comment]
I am liking this alternative.

How about this: do implement support for `CLDQM` in `LeapHybridDQMSampler` but in a generic, loosely coupled way:

1. wrap the `dqm.to_file(...)` call in `LeapHybridDQMSampler.sample_dqm()` with a `try ... except NotImplementedError` that calls `DQM.to_file(dqm, ...)` as a fallback.  Then there's no need to write a shallow copy/view method at all.  This handles the input side.
2. implement the sampleset transformation that the composite would do, in `CLDQM`, in a `_filter_sampleset()` method. `LeapHybridSampler` will pass the sampleset through this filter/transform if that method is defined on the dqm.  This handles the return side, and keeps the implementation details of the transform in `CLDQM`.

**Comment by seatim** [comment]
Looked into implementing `CLDQM._filter_sampleset()` and concluded that it's not the right approach here.  Putting arbitrary objects in a `numpy.recarray` is possible but will likely violate some assumptions and cause problems.  Decided that a utility method (`CLDQM.map_sample()`) is better.  That has been implemented in #844.

**Comment by seatim** [comment]
Cool, this is done from my perspective.

**Comment by arcondello** [comment]
Thanks @seatim!
