### ISSUE TITLE
dimod.bqm.adjvectorbqm module not found when building

### ISSUE THREAD

**Issue by mcfarljm** [dwavesystems/dimod#851]
**Description**
`ModuleNotFoundError` occurs when running `python setup.py install`.  Tail end of the output is:

```
  File "/home/jmcfarland/tmp/dimod/dimod/__init__.py", line 18, in <module>
    from dimod.bqm import *
  File "/home/jmcfarland/tmp/dimod/dimod/bqm/__init__.py", line 15, in <module>
    from dimod.bqm.adjvectorbqm import AdjVectorBQM
ModuleNotFoundError: No module named 'dimod.bqm.adjvectorbqm'
```

**Steps To Reproduce**
- Fresh virtualenv
- `pip install -r requirements.txt`
- `python setup.py install`

**Expected Behavior**
Successful build/install

**Environment**
 - OS: Debian 10
 - Python version: 3.7.3

**Comment by arcondello** [comment]
Try upgrading your `setuptools`? I have seen this before and that was the fix - I don't actually know why. If it fixes it for you as well I'll look into the cause.

**Comment by mcfarljm** [comment]
Thanks, that did it.  Was previously on `setuptools` 40.8.0, and upgrading went to 57.0.0.

**Comment by randomir** [comment]
Because PEP-517/518 support was added in [setuptools 42.0.0](https://setuptools.readthedocs.io/en/latest/history.html#v42-0-0).

**Comment by arcondello** [comment]
It's actually [setuptools 46.4.0](https://setuptools.readthedocs.io/en/latest/history.html#v46-4-0), specifically it's trying to import the package to get the `__version__`. We could support older versions of setuptools by moving `__version__` back to `dimod.package_info` and not having any other imports in that submodule.

For the record, 46.4.0 was released May 2020.

**Comment by arcondello** [comment]
Ah, looks like you already had that in https://github.com/dwavesystems/dwave-greedy/pull/16

**Comment by randomir** [comment]
That's correct.

We need `setuptools>=42.0.0` for build system from pyproject.toml to work (PEP-517/518). I.e. for build/cythonization requirements to be installed before build. In this bucket, I'll also put `pip>=10.0`, which is the first version to support pyproject.toml (a concern only when building from sdist or source).

And we need `setuptools>=46.4.0` for setup.cfg's `attr:` support.

**Comment by randomir** [comment]
FWIW, I invested (too much) time in figuring out all these edges, and dwave-greedy is the proto package I've been testing on (same for orbification). Standardized CI will be easy to propagate across Ocean packages via orbs, but standardizing the build/package config/details (and keeping them in sync) will be a pain.
