### ISSUE TITLE
Could You Support arm architecture?

### ISSUE THREAD

**Issue by 29rou** [dwavesystems/dimod#868]
**Application**

Support arm architecture.

**Proposed Solution**
[cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) allows you to do that.

**Comment by randomir** [comment]
Hi @29rou, thanks for contributing the issue and the PR.

We have already looked into shipping arm64 wheels (see this issue on Ocean SDK repo: https://github.com/dwavesystems/dwave-ocean-sdk/issues/126), and we looked at using cibuildwheel.

However, at the time it seemed better to wait for CircleCI to support custom docker images on arm64 than using the emulator, and to wait for cibuildwheel to support Windows on CircleCI. We might revisit that decision over time, as significance of arm64 wheels grows.

Currently, switching to GitHub Actions for CI (partially or fully) is not an attractive option.

**Comment by 29rou** [comment]
I understand. I'm sorry for the trouble I've caused you.
By the way, is it possible to support Apple Silicon and universal2?
Also, would it be possible to support an arm binary build without using Docker?

**Comment by randomir** [comment]
Thank you @29rou, these are great finds. We'll look into them. Unless you'd like to? Great first step would be enabling universal builds for macos, similar to how cibuildwheel does it (but consistent with our CircleCI workflow). We would love to see that PR :wink:

**Comment by 29rou** [comment]
Thanks, cibuildwheel's behavior on MacOS is not to use Docker. Therefore, I think it is safe to use cibuildwheel directly.
https://cibuildwheel.readthedocs.io/en/stable/setup/#circleci

**Comment by 29rou** [comment]
Of course, I would also like to investigate linux/arm64 cross-compilation and suggest it to you.

**Comment by 29rou** [comment]
On Mac, It would work well. 
And, Dimod would be builded by Xcode for M1 Mac.
``` 
export _PYTHON_HOST_PLATFORM=macosx-11.0-arm64
export ARCHFLAGS=-arch arm64
pip wheel .
```

**Comment by randomir** [comment]
Done in https://github.com/dwavesystems/dimod/pull/1290.
