### ISSUE TITLE
Use delvewheel and delocate

### ISSUE THREAD

**Issue by 29rou** [dwavesystems/dimod#870]
**Application**
You use auditwheel on Linux, but I think you should do the equivalent on other operating systems.
On Windows, You could use [delvewheel](https://pypi.org/project/delvewheel/). 
On MacOS, You could use [delocate](https://pypi.org/project/delocate/).

**Comment by randomir** [comment]
That's a great point! Thank you @29rou.

**Comment by randomir** [comment]
Possibly related: #669.

**Comment by 29rou** [comment]
Yes, I think You can fix the problem with that.

**Comment by arcondello** [comment]
We now use cibuildwheel, which uses delocate by default and will likely add delvewheel in the future (see https://github.com/pypa/cibuildwheel/issues/459)
