### ISSUE TITLE
`NewInteger` or `UniqueInteger` or similar

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#927]
It would be convenient to be able to generate QMs/BQMs/Variables with labels that are guaranteed to be unique. E.g.
```
i = UniqueInteger(lower_bound=0, upper_bound=8)
```

**Comment by hbarovertwo** [comment]
Should we think along the lines of a globally unique ID? We can generate those on the fly with: [https://docs.python.org/3/library/uuid.html](url)

**Comment by arcondello** [comment]
Yup, exactly like that I think. Are you interested in taking this one on?

**Comment by hbarovertwo** [comment]
Sure, I can start looking into it.
