### ISSUE TITLE
AdjVectorBQM serialization broken

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#932]
With dimod 0.10.4 (0.10.x), `AdjVectorBQM` *can not* be serialized:
```python
>>> import dimod
>>> bqm = dimod.BQM.from_ising({}, {'ab': 1})
>>> bqm.to_file()
<dimod.serialization.fileview.SpooledTemporaryFile object at 0x7fbdcd2b13d0>
>>> 
>>> bqm = dimod.AdjVectorBQM.from_ising({}, {'ab': 1})
__main__:1: DeprecationWarning: AdjVectorBQM(..) is deprecated and will be removed in dimod 0.11.0, please use BinaryQuadratic(.., dtype=np.float64) instead
>>> bqm.to_file()
__main__:1: DeprecationWarning: FileView is deprecated, please use `bqm.to_file` instead
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dimod/bqm/adjvectorbqm.pyx", line 1016, in dimod.bqm.adjvectorbqm.cyAdjVectorBQM.to_file
  File "/home/radomir/work/dwave-cloud-client-trunk/env/lib/python3.7/site-packages/dimod/serialization/fileview.py", line 135, in FileView
    return bqm.to_file(version=version, ignore_labels=ignore_labels)
TypeError: to_file() takes no keyword arguments
```

Works fine in dimod 0.9.x:
```python
>>> import dimod
>>> bqm = dimod.AdjVectorBQM.from_ising({}, {'ab': 1})
>>> bqm.to_file()
<dimod.serialization.fileview.FileView object at 0x7f64aed1f850>
```

---

The reason is double-recursive implementation of [`AdjVectorBQM.to_file`](https://github.com/dwavesystems/dimod/blob/9a8fdd04bacae8d5693970c45afcf7b1bca23bcc/dimod/bqm/adjvectorbqm.pyx#L1004)

https://github.com/dwavesystems/dimod/blob/9a8fdd04bacae8d5693970c45afcf7b1bca23bcc/dimod/bqm/adjvectorbqm.pyx#L1004-L1017

as it uses

https://github.com/dwavesystems/dimod/blob/9a8fdd04bacae8d5693970c45afcf7b1bca23bcc/dimod/serialization/fileview.py#L132-L135

which in turn calls the original to_file (with unsupported kwargs in addition).

**Comment by arcondello** [comment]
Duplicates https://github.com/dwavesystems/dimod/issues/898
