### ISSUE TITLE
Allow samples to have a superset of variables in energy calculations

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#949]
Especially with the inclusion of CQM, it would be good to allow samples provided to `.energy()` and `.energies()` functions to contain a superset of the variables in the relevant model.

An example of why this is useful:
Given a CQM
```python
x, y, z = Binaries('xyz')

cqm = ConstrainedQuadraticModel()

cqm.set_objective(y + z)
cqm.add_constraint(3*x >= 2)
cqm.add_constraint(-2*y + x == 0)
```
and proposed solution `{'x': 1, 'y': 0, 'z': 1}`, we cannot currently check the energy of any of the individual components. If we allowed energy checks to be more loose, we could do
```python
objective_energy = cqm.objective.energy(sample)
for constraint in cqm.constraints.values():
    constraint_lhs_energy = constraint.lhs.energy(sample)
```
*Additional Considerations*
We could toggle this behavior with a keyword argument. In which case my preference would be something like `strict` defaulting to `False`.

*Additional Context*
This contradicts part of https://github.com/dwavesystems/dimod/issues/244

**Comment by randomir** [comment]
Sounds intuitive. I would expect the `strict=False` behavior to work (if I was a new Ocean user).

And `strict=False` wouldn't be a backwards compat break, so :+1:

**Comment by pau557** [comment]
Nice, LGTM
