### ISSUE TITLE
Method to get the violation of each constraint given a sampleset

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#971]
Something like `cqm.violations() -> Mapping[Hashable, float]`. Can be done now with
```
violations = {}
for label, constraint in cqm.constraints.items():
    violations[label] = constraint.lhs.energy(sampleset) - constraint.rhs
```

**Comment by hsadeghidw** [comment]
When we solve a satisfiability problem, we can we will have objective or energy = 0, and there is no distinction between different solutions. It would be nice to be able to easily assess which solution violates less.

I think there should be two functions. `cqm.violations()` and `cqm.constraint_energies()` or something like that.

Here is the difference. 

for ==, the violation is the absolute of energy (or square of)
for <=, the violation is zero, if energy <= 0, otherwise, it's equal.

**Comment by arcondello** [comment]
The latter seems like the right "default" definition. We could potentially combine them into one method with something like
```python
class CQM:
    ...
    def iter_violations(self, clip=True) -> Iterator[Tuple[Hashable, float]]:
        if clip:
            yield from ((label, max(en, 0)) for label, en in self.iter_violations(clip=False))
        else:
            for label, constraint in cqm.constraints.items():
                yield label, constraint.lhs.energy(sampleset) - constraint.rhs


    def violations(self, clip=True) -> Dict[Hashable, float]:
        return dict(self.iter_violations(clip=clip))

```

**Comment by arcondello** [comment]
Trying that again:
```python
class CQM:
    ...
    def iter_violations(self) -> Iterator[Tuple[Hashable, float]]:
        for label, constraint in cqm.constraints.items():
            if constraint.sense is Sense.Le:
                yield label, constraint.lhs.energy(sampleset) - constraint.rhs
            elif constraint.sense is Sense.Ge:
                yield label, -min(constraint.lhs.energy(sampleset) - constraint.rhs)
            elif constraint.sense is Sense.Eq:
                yield label, abs(constraint.lhs.energy(sampleset) - constraint.rhs)
            else:
                raise RuntimeError("unexpected Sense")


    def violations(self) -> Dict[Hashable, float]:
        return dict(self.iter_violations(clip=clip))
```

**Comment by hsadeghidw** [comment]
Maybe I misunderstood the `clip` argument or maybe that's the wrong argument. I was expecting to see negative values for equality constraint when `clip=False`

```import dimod
import itertools
cqm = dimod.ConstrainedQuadraticModel()
x = dimod.Binary('x')
y = dimod.Binary('y')
z = dimod.Binary('z')
cqm.set_objective(-x-y-z)
cqm.add_constraint(x + y + z <= 2, label='c1')
cqm.add_constraint(x + y + z == 2, label='c2')

for values in itertools.product([0, 1], repeat=3):
    sol = {k: v for k, v in zip(cqm.variables, values)}
    print(sol, cqm.violations(sol),
          cqm.violations(sol, clip=False))
```

This produces:
```
{'x': 0, 'y': 0, 'z': 0} {'c1': 0.0, 'c2': 2.0} {'c1': -2.0, 'c2': 2.0}
{'x': 0, 'y': 0, 'z': 1} {'c1': 0.0, 'c2': 1.0} {'c1': -1.0, 'c2': 1.0}
{'x': 0, 'y': 1, 'z': 0} {'c1': 0.0, 'c2': 1.0} {'c1': -1.0, 'c2': 1.0}
{'x': 0, 'y': 1, 'z': 1} {'c1': 0.0, 'c2': 0.0} {'c1': 0.0, 'c2': 0.0}
{'x': 1, 'y': 0, 'z': 0} {'c1': 0.0, 'c2': 1.0} {'c1': -1.0, 'c2': 1.0}
{'x': 1, 'y': 0, 'z': 1} {'c1': 0.0, 'c2': 0.0} {'c1': 0.0, 'c2': 0.0}
{'x': 1, 'y': 1, 'z': 0} {'c1': 0.0, 'c2': 0.0} {'c1': 0.0, 'c2': 0.0}
{'x': 1, 'y': 1, 'z': 1} {'c1': 1.0, 'c2': 1.0} {'c1': 1.0, 'c2': 1.0}
```

I like to be able to say that x+y+z - 2 (regardless of `==` or `<=`) has a current value/energy/evaluation of -2 or -1, or 0, etc. The violation is correct (the abs(value) for equality and value if value >= 0 for inequality).

**Comment by arcondello** [comment]
I am confused why there would be negative values for equality constraints? This value is returning the "violation" of the constraint, and if the lhs != the rhs, then the violation is positive.

If you just want `lhs - rhs`, then we also should not swap the sign on the `>=`. Otherwise we are not being consistent in what we mean by violation.

**Comment by arcondello** [comment]
To expand, there are two self-consistent ways we can encode this information:
1) Always return the lhs - rhs. So
a) `1 <= 5` -> `-4`
b)  `1 >= 5` -> `-4`
c)  `1 == 5` -> `-4`
2) Treat "the amount of feasibility" as negative and the "amount of infeasibility" as positive
a) `1 <= 5` -> `-4` since it's satified
b)  `1 >= 5` -> `4` since it's violated
c)  `1 == 5` -> `4` since it's violated

If we want to do (1) then IMO we should make a separate method `cqm.iter_lhs_minus_rhs()` or the like, if we want (2) then I would implement it as I have in #975 . We can also have both :shrug:

**Comment by hsadeghidw** [comment]
The issue with the second suggestion is that it hides the direction of infeasibility for equality constraints. 

My suggestion
- Maybe we need a second method that isn't called "violation" and it simply returns the raw lhs-rhs (understood as the left of <= or ==)
- remove clip, because that's not what I had in mind (or keep it if you think would be useful in other situations)

**Comment by arcondello** [comment]
I am resistant to reinterpreting the `>=` as `<=` as the default behavior. I understand why that may be convenient in some cases but IMO that's exactly the kind of special case that causes lots of user confusion.

I suppose an ugly, but explicit way would be
(a) `cqm.violations(..., signed_equality=True)`. Terrible keyword name but you get the point.
(b) `cqm.lhs_minus_rhs(..., reinterpret_ge=True)`. Again bad name, but you get the idea.
