### ISSUE TITLE
CQM to BQM conversion to return objects that can be stored

### ISSUE THREAD

**Issue by pau557** [dwavesystems/dimod#977]
https://github.com/dwavesystems/dimod/blob/74ac365d281ffc8ec20fdbe4bd02008e7ec6db91/dimod/constrained.py#L1118

In order to give this more functionality, one should be able to store the conversion-relevant information for later use. So instead of returning an inverter object that needs to be kept alive, it could return an information dictionary to be passed to the inverter at some other time.

I propose something like this:
```python
    conversion_info=dict(binary=binary, integers=integers)
    return bqm, conversion_info
```
So that later one does this:

```python
inverter = CQMToBQMInverter(**conversion_info)
```

Great asset if the conversion_info is JSON friendly. Ie. use Vartype.XXXX.name instead of the vartype itself

**Comment by arcondello** [comment]
I think something like
```
doc = inverter.to_dict()
inverter = CQMToBQMInverter.from_dict(doc)
```
is very doable.

**Comment by pau557** [comment]
that is the obvious way 👍
